(Generated by rs_cam)
G17 G21 G90 G40 G49 G80
G54
M5
(MSG,TOOL CHANGE: Tool One [T1])
M6 T1
M3 S18000
(LOAD: Tool One [T1])
(=== Top ===)
(Pocket)
G0 Z5.000
G0 X0.000 Y0.000 Z5.000
G1 X10.000 Y0.000 Z-2.000 F600
G1 X10.000 Y10.000 Z-2.000
G0 Z25.000
M5
(MSG,M0 hold: no jog. To re-zero, export one file per setup.)
(MSG,Setup change: Bottom)
M0
M3 S18000
(=== Bottom ===)
(Profile)
G0 Z5.000
G0 X20.000 Y0.000 Z5.000
G1 X30.000 Y0.000 Z-1.000 F300
G1 X30.000 Y10.000 Z-1.000
G0 Z25.000
M5
M30
