#!/usr/bin/env python3
"""G2: write fetch/G2/sources.json from the builder's stored index plus the
coverage notes below. Run after g2_build.py."""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
G2 = os.path.normpath(os.path.join(HERE, "..", "fetch", "G2"))
idx = json.load(open(os.path.join(G2, ".stored_index.json")))  # written by g2_build.py
stored, nrows = idx["stored"], idx["rows_per_source"]
A = "2026-09-24"
META = {
 "onsrud_hard_wood_cutting_data": ("onsrud", "LMT Onsrud Hard Wood Cutting Data Recommendations (catalog page 115)", "https://www.onsrud.com/images/Hard%20Wood.pdf",
   "Same PDF as the LUT copy (pdf_sha256 and pdftotext text identical to crates/rs_cam_core/data/vendor_lut/sources/onsrud_hard_wood_cutting_data.txt). NEW for G2: the sheet prints V-bit series 37-50 (90 deg V bottom, solid carbide, 2F) at 3/16, 1/4, 3/8 in; 37-60 (90 deg V bottom, carbide tipped, 2F) at 3/8, 1/2, 3/4, 1 in; 37-80 (lettering, 2F) at 1, 1 1/4*, 2** in; 37-00/37-20 (engraving, 1F) under the 1/4 in (shank) column. The LUT holds none of these rows."),
 "onsrud_soft_wood_cutting_data": ("onsrud", "LMT Onsrud Soft Wood Cutting Data Recommendations (catalog page 114)", "https://www.onsrud.com/images/Soft%20Wood.pdf",
   "Same PDF as the LUT copy (identical sha and text). Prints the same 37-series V-bit rows as the other wood sheets, with the same values."),
 "onsrud_mdf_cutting_data": ("onsrud", "LMT Onsrud MDF Cutting Data Recommendations (catalog page 116)", "https://www.onsrud.com/images/MDF.pdf",
   "Same PDF as the LUT copy (identical sha and text). Prints the 37-series V-bit rows: the first printed V-bit chipload in MDF from Onsrud. Cell positions checked on a 200 dpi render."),
 "onsrud_hard_plywood_cutting_data": ("onsrud", "LMT Onsrud Hard Plywood Cutting Data Recommendations (catalog page 118)", "https://www.onsrud.com/images/Hard%20Plywood.pdf",
   "Same PDF as the LUT copy (identical sha and text). Prints the 37-series V-bit rows (V-bit in hard plywood) and the 77-100 tapered ball row (already in the LUT)."),
 "onsrud_soft_plywood_cutting_data": ("onsrud", "LMT Onsrud Soft Plywood Cutting Data Recommendations (catalog page 117)", "https://www.onsrud.com/images/Soft%20Plywood.pdf",
   "Same PDF as the LUT copy (identical sha and text). Prints the 37-series V-bit rows (V-bit in soft plywood). No 77-100 row, no ball nose."),
 "onsrud_laminated_chipboard_cutting_data": ("onsrud", "LMT Onsrud Laminated Chipboard Cutting Data Recommendations (catalog page 119, upper table)", "https://www.onsrud.com/images/Laminated%20Chipboard.pdf",
   "NEW source (linked from https://www.onsrud.com/Forms/Cutting-Data-Recommendations.asp). The PDF is the whole catalog page 119: its text layer holds BOTH the Laminated Chipboard and the Laminated Plywood tables (the Laminated Plywood PDF is the same page, another crop, another sha). Depth rule: 'Greater than 3 x D, reduce chip load by 25%'. Prints 37-00/37-20, 37-50, 37-60, 37-80 and flat series 48-000, 57-200, 57-200MD, 60-100MW/C/MC/PLR, 60-600, 68-100. The 37-60 row sits under 3/8, 9/16 and 7/8 in (render-checked), which matches no 37-60 catalog size: probable layout error, transcribed as printed. No ball nose, no tapered ball."),
 "onsrud_laminated_plywood_cutting_data": ("onsrud", "LMT Onsrud Laminated Plywood Cutting Data Recommendations (catalog page 119, lower table)", "https://www.onsrud.com/images/Laminated%20Plywood.pdf",
   "NEW source. Same catalog page 119 as the Laminated Chipboard PDF (both tables in one text layer; different crop and sha). Rows are read from the second (lower) table. Prints 37-series V-bits at the same positions and values as the wood sheets (37-80 at 1, 1 1/2, 2 in, no RPM marks). No ball nose, no tapered ball."),
 "onsrud_pct19_catalog": ("onsrud", "LMT Onsrud Production Cutting Tools Catalog PCT-19 (Wood, Plastic, Composite, Honeycomb, Aluminum)", "https://onsrud.com/images/LMT%20Onsrud%20Product%20Cutting%20Tools%20Catalog%20PCT-19.pdf",
   "Tool definitions only (no candidate rows). Stored text is an EXCERPT: pdftotext pages 20-22 (37-00/37-20 engraving: 1 flute, 60/30 deg, tip 0.005-0.040 in, 1/4 in shank; 37-50: 2F solid carbide V bottom, CD 3/16, 1/4, 3/8 in; 37-60: 2F carbide tipped V bottom, CD 1/2, 3/4, 1 in, 'Designed for V grooving or beveling 90 deg'; 37-80 lettering: 37-82 1 in 60 deg, 37-87 1-1/2 in 90 deg, 37-92 2 in 120 deg, 37-97 2 in 140 deg, all 2F) and page 119 (laminated tables). The 132-page catalog also carries the same cutting-data pages as the per-material PDFs (identical 37-series values). 20.9 MB PDF; sha covers the whole file."),
 "amana_pcd_ball_nose_v2": ("amana", "Amana Polycrystalline Diamond (PCD) Ball Nose Router Bit Speed Chart v2", "https://www.amanatool.com/pub/media/productattachments/PCD-Ball-Nose-Speed-Chart-v2.pdf",
   "NEW source. PCD ball nose DRB-432 (1/4 in) and DRB-433 (3/8 in), 2 teeth, rows CFRP, Plastics, Wood, MDF, Chipboard Without Coating, with chipload and RPM ranges printed in inch and mm. The only printed ball-nose chart found with a chipboard (particleboard) row. MDF band is BELOW the Wood band on both sizes (1/4: MDF .0016-.005 vs Wood .002-.007; 3/8: MDF .005-.008 vs Wood .006-.01); Chipboard equals Wood. No plywood row. PCD, not carbide."),
 "amana_spektra_3d_profiling_v6": ("amana", "Amana Spektra Extreme Tool Life Coated 2D/3D Carving CNC Solid Carbide Router Bits, Feed and Chip Load Chart v6", "https://www.amanatool.com/pub/media/productattachments/Spektra-Coated-3D-Profiling-Feed-Chip-Load-Chart-v6.pdf",
   "NEW source. Ball nose 2F 1/4, 3F 1/32 and 1/8, 4F 1/16 and 1/8 (ball & flat bottom), 3F extra long 1/4 (ball & flat bottom), at 18,000 RPM. Every wood value is printed in ONE row 'Wood, MDF, Sign-Foam': the vendor makes no MDF / wood distinction on these tools. No plywood mention. Same layout and the SAME values as the ZrN 3D profiling chart the LUT holds (amana_zrn_3d_profiling) for the matching tools, so it is not an independent witness. The LUT emits the ZrN 'Wood, MDF, Sign-Foam' row as both mdf and softwood rows; this fetch emits mdf rows only."),
 "amana_ball_nose_v7": ("amana", "Amana Spiral Ball Nose Speed Chart v7", "https://www.amanatool.com/pub/media/productattachments/Spiral-Ball-Nose-Speed-Chart-v7.pdf",
   "Re-downloaded; pdf_sha256 and text identical to the LUT copy. Prints Softwood, Hardwood and MDF (and plastics, aluminum, sign foam) at 1/16 to 3/4 in; no plywood row. The LUT transcribes only the 1/8 and 1/4 in columns; the 15 candidate rows are the other printed wood/MDF sizes. MDF >= Hardwood at every size; MDF = Softwood at 1/16 and 1/8, MDF < Softwood from 1/4 up."),
 "amana_spiral_ball_nose_v6": ("amana", "Amana Spiral Ball Nose Speed Chart v6", "https://www.amanatool.com/pub/media/productattachments/Spiral-Ball-Nose-Speed-Chart-v6.pdf",
   "Corroboration only (no rows). The Softwood, Hardwood and MDF lines are identical to v7."),
 "amana_spiral_ball_nose_2015": ("amana", "Amana Solid Carbide CNC Spiral Ball Nose Router Bits Speed and Feed Chart (copyright 2015)", "https://toolstoday.com/content/ProductFile/Attachments/Spiral-Ball-Nose-Speed-Chart.pdf",
   "Corroboration only (no rows); reseller-hosted older edition. Softwood, Hardwood, MDF chiploads identical to v6/v7; no plywood row."),
 "freud_router_bit_feed_and_speed_for_cnc_20170822": ("freud", "Freud: Get the most out of your Freud bits by routing at ideal feed rates and speeds (2017-08-22)", "https://www.freudtools.com/public/assets/freud/downloadables/freudtools-router-bit-feed-and-speed-for-cnc-20170822.pdf",
   "The LUT cites this chart but stores no text or sha; this is the first stored copy. Two tables: solid carbide router bits and carbide tipped straight and profile bits, 1/8-1/2 in (CT 1/8-3/4 in), columns MDF/Particle Board, Laminated Particle Board, Hardwood, Softwood, Acrylics/Soft Plastic, Solid Surface/Hard Plastic, Plywood, Aluminum. Tool type is generic (no ball nose, no V-groove named). Useful for G2 as a flat-family category ratio across 6 wood-type columns. No new candidate rows (flat family is not a G2 gap); see lut_discrepancies.md."),
 "leitz_lexicon7_05_routing": ("leitz", "Leitz Lexicon Edition 7, 05 Routing (Version 3, 05/2026)", "https://www.leitz.org/fileadmin/Downloads/Lexicon/EN/Leitz_Lexicon_Edition_7_-_05_Routing.pdf",
   "Target 2 statements, no rows. Stored text is an EXCERPT: only the pages that print 'Correction factor for vf'. Each vf diagram names a base 'Workpiece material' at a fixed speed n; the factor scales vf for another material. Base plastic-coated chipboard: 'MDF = 0.8' (most diagrams), 'MDF = 0.9' (jointing), 'MDF = 0.6' (one diagram), 'Uncoated chipboard = 1.1', 'Solid wood = 0.8' (grooving), 'Pre trimming MDF = 1.2'. Base softwood (sizing/jointing): 'Hardwood = 0.8; Chipboard = 1.3; Glulam = 0.9', 'Hardwood = 0.8; Chipboard = 1.2', 'Hardwood = 0.9; ... Chipboard = 1.1', 'Hardwood = 0.7; Glulam = 0.8'. NO plywood factor anywhere in the volume. Tools are industrial sizing/grooving/jointing cutters (straight, turnblade, diamond), not ball nose or V-bit. Reading a vf factor at fixed n and Z as an fz factor is an inference (derived)."),
 "techno_cnc_chipload_rev2": ("techno_cnc", "Techno CNC Chip Load Chart Rev 2", "https://technocnc.com/wp-content/uploads/2023/03/Techno-CNC_Chip-Load-Data_Rev-2-1.pdf",
   "Machine builder and tool seller; tool type not stated (grade c at best, no rows). Category statement: the columns are 'Hard Wood', 'Softwood & Plywood', 'MDF & Particle Board'; plywood shares the softwood column and MDF shares with particleboard. MDF & Particle Board equals Softwood & Plywood at 1/4 in (.010-.013) and is within one band step elsewhere."),
 "sienci_feeds_speeds_imperial": ("sienci", "Sienci Labs Feeds and Speeds (Imperial)", "https://resources.sienci.com/wp-content/uploads/2022/03/Feeds-and-Speeds-Imperial.pdf",
   "Hobby machine builder; feed rates and RPM only, no chipload, no flute count (grade c, no rows). Category statement: two tables, 'Softwood/Soft Plywood/MDF' and 'Hardwood / Hard Plywood'; the V-bit and ball end mill lines appear in both. Plywood is grouped with the solid wood of its face class; MDF is grouped with softwood."),
 "sorotec_schnittwerte": ("sorotec", "Sorotec Schnittwerte / Richtwerte fuer Drehzahl und Vorschub", "https://webseite.sorotec.de/download/fraesparameter/schnittwerte.pdf",
   "Reseller guide (grade c, no rows); tool type not stated; 'Die aufgefuehrten Werte dienen der groben Orientierung'. Rows 'Holz Hart', 'Holz weich', 'MDF' by diameter 1-12 mm. MDF is 2x to 6x the wood rows (e.g. 6 mm: Holz Hart 0,055, Holz weich 0,060, MDF 0,300 mm/Zahn). No plywood row. An outlier against every other source."),
 "shopbot_feedsandspeeds_2016": ("shopbot", "ShopBot Tools Feeds and Speeds Charts (July 21, 2016)", "https://shopbottools.com/wp-content/uploads/2024/01/FeedsandSpeeds.pdf",
   "Secondary copy of Onsrud numbers for the ShopBot bit kit (grade c, no rows): 'These charts have been taken from Onsrud's recommendations'. Tables for Soft wood, Hard wood, MDF, Soft Plywood, Laminated Chipboard, Laminated Plywood. The 1 in 60 degree Carbide V cutter (Onsrud 37-82) is .004-.006 in every table; the 1/8 in tapered ball (77-102) is .003-.005 in hard wood, soft wood, MDF and laminated plywood and n/a in soft plywood and laminated chipboard. Corroborates the Onsrud 37-80 1 in cell."),
 "ansi_a208_1_2016_particleboard": ("cpa", "ANSI A208.1-2016 Particleboard (Composite Panel Association)", "https://res.cloudinary.com/hdi/image/upload/v1621251940/Suppliers/Guides/CPA_ANSI_Standard_A208_1_Particleboard_2016.pdf",
   "Janka proxy source for particleboard (no rows). 4.3.7: hardness per ASTM D1037-12 Section 17. Table A (industrial grades H-1..M-3i, LD) prints NO hardness column in this edition. Table B (flooring / building-code grades PBU, D-2, D-3, M-3) prints Hardness 2225 N (500 lb) as a requirement (minimum), not a typical value. Reseller-hosted copy of the standard."),
 "wood_handbook_1999_ch10": ("usda_fpl", "Wood Handbook (FPL-GTR-113, 1999), Chapter 10 Wood-based Composites and Panel Products (Youngquist); third-party mirror", "https://www.drjengineering.org/sites/default/files/uploads/attachments/field_collection/563/fpl_wood_handbook_ch10.pdf",
   "Janka proxy source (no rows). Table 10-8 (from NPA 1993): particleboard hardness requirement H-1 2,225 N, H-2 4,450 N, H-3 6,675 N, M-1/M-S/M-2/M-3 2,225 N, LD NS. Table 10-9: PBU, D-2, D-3 2,225 N. Table 10-10 (MDF, ANSI A208.2, NPA 1994): NO hardness column. The fpl.fs.usda.gov originals (GTR-190, GTR-282 chapters) returned an HTML block page to curl; this mirror of the 1999 chapter was the reachable copy."),
 "weyerhaeuser_mdf_spec": ("weyerhaeuser", "Weyerhaeuser Specifications for Standard MDF Products", "https://www.weyerhaeuser.com/application/files/1715/2631/5929/WEY-MDF-Standard-Product-Specifications.pdf",
   "Negative result for the MDF Janka proxy: the mill specification prints density (49.0 lb/ft3, 788 kg/m3 under 0.551 in) and ANSI A208.2 properties but no hardness."),
}
out = []
for sid, (vendor, title, url, cov) in META.items():
    st, sh = stored[sid]
    cov2 = cov + f" Candidate rows from this source: {nrows.get(sid, 0)}."
    out.append({"source_id": sid, "source_vendor": vendor, "source_title": title, "source_url": url,
                "accessed_on": A, "stored_text": st, "pdf_sha256": sh, "coverage_notes": cov2})
assert set(META) == set(stored), set(stored) ^ set(META)
json.dump(out, open(os.path.join(G2, "sources.json"), "w"), indent=1, ensure_ascii=False)
print(len(out), "sources")
