(Generated by rs_cam)
G17 G21 G90 G40 G49 G80
G54
M3 S18000
(=== Top ===)
(Top pocket)
G0 X0.000 Y0.000 Z5.000
G1 X10.000 Y0.000 Z-2.000 F600
G0 Z25.000
M5
(Setup change: Bottom
Flip stock 180 then resume)
M0
M3 S18000
(=== Bottom
Flip stock 180 then resume ===)
(Bottom profile)
G0 X20.000 Y0.000 Z5.000
G1 X30.000 Y0.000 Z-2.000 F600
M5
G0 Z10.000
M30
