(Generated by rs_cam)
G17 G21 G90 G40 G49 G80
G54
M3 S18000
(LOAD: Tool Three [T3])
(Op 0 — left-comp profile)
G0 Z5.000
G0 X0.000 Y0.000 Z5.000
(WARNING: cutter compensation unsupported on GRBL; dropped: G41 D3)
G1 X0.000 Y0.000 Z-2.000 F300
G1 X20.000 Y0.000 Z-2.000 F600
G1 X20.000 Y20.000 Z-2.000
G1 X0.000 Y20.000 Z-2.000
G1 X0.000 Y0.000 Z-2.000
G1 X0.000 Y0.000 Z5.000 F1000
(WARNING: cutter compensation unsupported on GRBL; dropped: G40)
M5
M30
