//! G-code generation and post-processors.

use crate::toolpath::{MoveType, Toolpath};
use std::fmt::Write;

/// Post-processor trait for machine-specific G-code dialects.
pub trait PostProcessor {
    fn name(&self) -> &str;
    fn preamble(&self, spindle_rpm: u32) -> String;
    fn postamble(&self) -> String;
    fn rapid(&self, x: f64, y: f64, z: f64) -> String;
    fn linear(&self, x: f64, y: f64, z: f64, feed: f64) -> String;
    fn arc_cw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String;
    fn arc_ccw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String;
    fn comment(&self, text: &str) -> String;
    fn decimal_places(&self) -> usize { 3 }
}

/// GRBL-compatible post-processor.
pub struct GrblPost;

impl PostProcessor for GrblPost {
    fn name(&self) -> &str { "GRBL" }

    fn preamble(&self, spindle_rpm: u32) -> String {
        let mut s = String::new();
        writeln!(s, "(Generated by rs_cam)").unwrap();
        writeln!(s, "G17 G21 G90 G40 G49 G80").unwrap();
        writeln!(s, "M3 S{spindle_rpm}").unwrap();
        s
    }

    fn postamble(&self) -> String {
        let mut s = String::new();
        writeln!(s, "M5").unwrap();
        writeln!(s, "G0 Z10.000").unwrap();
        writeln!(s, "M30").unwrap();
        s
    }

    fn rapid(&self, x: f64, y: f64, z: f64) -> String {
        format!("G0 X{x:.3} Y{y:.3} Z{z:.3}\n")
    }

    fn linear(&self, x: f64, y: f64, z: f64, feed: f64) -> String {
        format!("G1 X{x:.3} Y{y:.3} Z{z:.3} F{feed:.0}\n")
    }

    fn arc_cw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String {
        format!("G2 X{x:.3} Y{y:.3} Z{z:.3} I{i:.3} J{j:.3} F{feed:.0}\n")
    }

    fn arc_ccw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String {
        format!("G3 X{x:.3} Y{y:.3} Z{z:.3} I{i:.3} J{j:.3} F{feed:.0}\n")
    }

    fn comment(&self, text: &str) -> String {
        format!("({text})\n")
    }
}

/// LinuxCNC-compatible post-processor.
pub struct LinuxCncPost;

impl PostProcessor for LinuxCncPost {
    fn name(&self) -> &str { "LinuxCNC" }

    fn preamble(&self, spindle_rpm: u32) -> String {
        let mut s = String::new();
        writeln!(s, "(Generated by rs_cam)").unwrap();
        writeln!(s, "G17 G21 G90 G40 G49 G80").unwrap();
        writeln!(s, "G54").unwrap();
        writeln!(s, "M3 S{spindle_rpm}").unwrap();
        s
    }

    fn postamble(&self) -> String {
        let mut s = String::new();
        writeln!(s, "M5").unwrap();
        writeln!(s, "G53 G0 Z0").unwrap();
        writeln!(s, "M2").unwrap();
        s
    }

    fn rapid(&self, x: f64, y: f64, z: f64) -> String {
        format!("G0 X{x:.4} Y{y:.4} Z{z:.4}\n")
    }

    fn linear(&self, x: f64, y: f64, z: f64, feed: f64) -> String {
        format!("G1 X{x:.4} Y{y:.4} Z{z:.4} F{feed:.1}\n")
    }

    fn arc_cw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String {
        format!("G2 X{x:.4} Y{y:.4} Z{z:.4} I{i:.4} J{j:.4} F{feed:.1}\n")
    }

    fn arc_ccw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String {
        format!("G3 X{x:.4} Y{y:.4} Z{z:.4} I{i:.4} J{j:.4} F{feed:.1}\n")
    }

    fn comment(&self, text: &str) -> String {
        format!("({text})\n")
    }

    fn decimal_places(&self) -> usize { 4 }
}

/// Emit G-code from a toolpath using the given post-processor.
pub fn emit_gcode(
    toolpath: &Toolpath,
    post: &dyn PostProcessor,
    spindle_rpm: u32,
) -> String {
    let mut output = String::new();

    output.push_str(&post.preamble(spindle_rpm));

    let mut last_feed: Option<f64> = None;

    for m in &toolpath.moves {
        match m.move_type {
            MoveType::Rapid => {
                output.push_str(&post.rapid(m.target.x, m.target.y, m.target.z));
                last_feed = None;
            }
            MoveType::Linear { feed_rate } => {
                if last_feed != Some(feed_rate) {
                    output.push_str(&post.linear(
                        m.target.x,
                        m.target.y,
                        m.target.z,
                        feed_rate,
                    ));
                    last_feed = Some(feed_rate);
                } else {
                    let dp = post.decimal_places();
                    write!(
                        output,
                        "G1 X{:.dp$} Y{:.dp$} Z{:.dp$}\n",
                        m.target.x, m.target.y, m.target.z
                    )
                    .unwrap();
                }
            }
            MoveType::ArcCW { i, j, feed_rate } => {
                output.push_str(&post.arc_cw(
                    m.target.x, m.target.y, m.target.z, i, j, feed_rate,
                ));
                last_feed = Some(feed_rate);
            }
            MoveType::ArcCCW { i, j, feed_rate } => {
                output.push_str(&post.arc_ccw(
                    m.target.x, m.target.y, m.target.z, i, j, feed_rate,
                ));
                last_feed = Some(feed_rate);
            }
        }
    }

    output.push_str(&post.postamble());
    output
}

/// Get a post-processor by name.
pub fn get_post_processor(name: &str) -> Option<Box<dyn PostProcessor>> {
    match name.to_lowercase().as_str() {
        "grbl" => Some(Box::new(GrblPost)),
        "linuxcnc" => Some(Box::new(LinuxCncPost)),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::geo::P3;
    use crate::toolpath::Toolpath;

    #[test]
    fn test_grbl_gcode() {
        let mut tp = Toolpath::new();
        tp.rapid_to(P3::new(0.0, 0.0, 10.0));
        tp.feed_to(P3::new(10.0, 0.0, 0.0), 1000.0);
        tp.feed_to(P3::new(20.0, 0.0, 0.0), 1000.0);

        let gcode = emit_gcode(&tp, &GrblPost, 18000);

        assert!(gcode.contains("G17 G21 G90"));
        assert!(gcode.contains("M3 S18000"));
        assert!(gcode.contains("G0 X0.000 Y0.000 Z10.000"));
        assert!(gcode.contains("G1 X10.000 Y0.000 Z0.000 F1000"));
        // Second G1 should omit F (modal)
        assert!(gcode.contains("G1 X20.000 Y0.000 Z0.000\n"));
        assert!(gcode.contains("M5"));
        assert!(gcode.contains("M30"));
    }
}
