//! G-code generation and post-processors.
//!
//! Note: `let _ = write!(...)` is used throughout this module for writing to `String`.
//! Writing to `String` is infallible (only fails on OOM, which panics regardless),
//! so discarding the `Result` with `let _ =` is safe.

use crate::toolpath::{MoveType, Toolpath};
use std::fmt::Write;

/// Post-processor trait for machine-specific G-code dialects.
pub trait PostProcessor {
    fn name(&self) -> &str;
    fn preamble(&self, spindle_rpm: u32) -> String;
    fn postamble(&self) -> String;
    fn rapid(&self, x: f64, y: f64, z: f64) -> String;
    fn linear(&self, x: f64, y: f64, z: f64, feed: f64) -> String;
    fn arc_cw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String;
    fn arc_ccw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String;
    fn comment(&self, text: &str) -> String;
    fn decimal_places(&self) -> usize { 3 }
}

/// GRBL-compatible post-processor.
pub struct GrblPost;

impl PostProcessor for GrblPost {
    fn name(&self) -> &str { "GRBL" }

    fn preamble(&self, spindle_rpm: u32) -> String {
        let mut s = String::new();
        let _ = writeln!(s, "(Generated by rs_cam)");
        let _ = writeln!(s, "G17 G21 G90 G40 G49 G80");
        let _ = writeln!(s, "M3 S{spindle_rpm}");
        s
    }

    fn postamble(&self) -> String {
        let mut s = String::new();
        let _ = writeln!(s, "M5");
        let _ = writeln!(s, "G0 Z10.000");
        let _ = writeln!(s, "M30");
        s
    }

    fn rapid(&self, x: f64, y: f64, z: f64) -> String {
        format!("G0 X{x:.3} Y{y:.3} Z{z:.3}\n")
    }

    fn linear(&self, x: f64, y: f64, z: f64, feed: f64) -> String {
        format!("G1 X{x:.3} Y{y:.3} Z{z:.3} F{feed:.0}\n")
    }

    fn arc_cw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String {
        format!("G2 X{x:.3} Y{y:.3} Z{z:.3} I{i:.3} J{j:.3} F{feed:.0}\n")
    }

    fn arc_ccw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String {
        format!("G3 X{x:.3} Y{y:.3} Z{z:.3} I{i:.3} J{j:.3} F{feed:.0}\n")
    }

    fn comment(&self, text: &str) -> String {
        format!("({text})\n")
    }
}

/// LinuxCNC-compatible post-processor.
pub struct LinuxCncPost;

impl PostProcessor for LinuxCncPost {
    fn name(&self) -> &str { "LinuxCNC" }

    fn preamble(&self, spindle_rpm: u32) -> String {
        let mut s = String::new();
        let _ = writeln!(s, "(Generated by rs_cam)");
        let _ = writeln!(s, "G17 G21 G90 G40 G49 G80");
        let _ = writeln!(s, "G54");
        let _ = writeln!(s, "M3 S{spindle_rpm}");
        s
    }

    fn postamble(&self) -> String {
        let mut s = String::new();
        let _ = writeln!(s, "M5");
        let _ = writeln!(s, "G53 G0 Z0");
        let _ = writeln!(s, "M2");
        s
    }

    fn rapid(&self, x: f64, y: f64, z: f64) -> String {
        format!("G0 X{x:.4} Y{y:.4} Z{z:.4}\n")
    }

    fn linear(&self, x: f64, y: f64, z: f64, feed: f64) -> String {
        format!("G1 X{x:.4} Y{y:.4} Z{z:.4} F{feed:.1}\n")
    }

    fn arc_cw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String {
        format!("G2 X{x:.4} Y{y:.4} Z{z:.4} I{i:.4} J{j:.4} F{feed:.1}\n")
    }

    fn arc_ccw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String {
        format!("G3 X{x:.4} Y{y:.4} Z{z:.4} I{i:.4} J{j:.4} F{feed:.1}\n")
    }

    fn comment(&self, text: &str) -> String {
        format!("({text})\n")
    }

    fn decimal_places(&self) -> usize { 4 }
}

/// Emit G-code from a toolpath using the given post-processor.
pub fn emit_gcode(
    toolpath: &Toolpath,
    post: &dyn PostProcessor,
    spindle_rpm: u32,
) -> String {
    let mut output = String::new();

    output.push_str(&post.preamble(spindle_rpm));

    let mut last_feed: Option<f64> = None;

    for m in &toolpath.moves {
        match m.move_type {
            MoveType::Rapid => {
                output.push_str(&post.rapid(m.target.x, m.target.y, m.target.z));
                last_feed = None;
            }
            MoveType::Linear { feed_rate } => {
                if last_feed != Some(feed_rate) {
                    output.push_str(&post.linear(
                        m.target.x,
                        m.target.y,
                        m.target.z,
                        feed_rate,
                    ));
                    last_feed = Some(feed_rate);
                } else {
                    let dp = post.decimal_places();
                    let _ = writeln!(
                        output,
                        "G1 X{:.dp$} Y{:.dp$} Z{:.dp$}",
                        m.target.x, m.target.y, m.target.z
                    );
                }
            }
            MoveType::ArcCW { i, j, feed_rate } => {
                output.push_str(&post.arc_cw(
                    m.target.x, m.target.y, m.target.z, i, j, feed_rate,
                ));
                last_feed = Some(feed_rate);
            }
            MoveType::ArcCCW { i, j, feed_rate } => {
                output.push_str(&post.arc_ccw(
                    m.target.x, m.target.y, m.target.z, i, j, feed_rate,
                ));
                last_feed = Some(feed_rate);
            }
        }
    }

    output.push_str(&post.postamble());
    output
}

/// Mach3-compatible post-processor.
pub struct Mach3Post;

impl PostProcessor for Mach3Post {
    fn name(&self) -> &str { "Mach3" }

    fn preamble(&self, spindle_rpm: u32) -> String {
        let mut s = String::new();
        let _ = writeln!(s, "(Generated by rs_cam)");
        let _ = writeln!(s, "G17 G21 G90 G40 G80");
        let _ = writeln!(s, "M3 S{spindle_rpm}");
        let _ = writeln!(s, "G4 P2"); // dwell for spindle spin-up
        s
    }

    fn postamble(&self) -> String {
        let mut s = String::new();
        let _ = writeln!(s, "M5");
        let _ = writeln!(s, "G0 Z10.000");
        let _ = writeln!(s, "G28 G91 Z0");
        let _ = writeln!(s, "M30");
        s
    }

    fn rapid(&self, x: f64, y: f64, z: f64) -> String {
        format!("G0 X{x:.4} Y{y:.4} Z{z:.4}\n")
    }

    fn linear(&self, x: f64, y: f64, z: f64, feed: f64) -> String {
        format!("G1 X{x:.4} Y{y:.4} Z{z:.4} F{feed:.1}\n")
    }

    fn arc_cw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String {
        format!("G2 X{x:.4} Y{y:.4} Z{z:.4} I{i:.4} J{j:.4} F{feed:.1}\n")
    }

    fn arc_ccw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String {
        format!("G3 X{x:.4} Y{y:.4} Z{z:.4} I{i:.4} J{j:.4} F{feed:.1}\n")
    }

    fn comment(&self, text: &str) -> String {
        format!("({text})\n")
    }

    fn decimal_places(&self) -> usize { 4 }
}

/// A phase in a multi-operation job: toolpath + spindle speed + label.
pub struct GcodePhase<'a> {
    pub toolpath: &'a Toolpath,
    pub spindle_rpm: u32,
    pub label: &'a str,
}

/// Emit G-code from multiple phases, inserting spindle speed changes between operations.
pub fn emit_gcode_phased(
    phases: &[GcodePhase<'_>],
    post: &dyn PostProcessor,
) -> String {
    if phases.is_empty() {
        return String::new();
    }

    let mut output = String::new();
    let first_rpm = phases[0].spindle_rpm;
    output.push_str(&post.preamble(first_rpm));

    let mut current_rpm = first_rpm;
    let mut last_feed: Option<f64> = None;

    for phase in phases {
        output.push_str(&post.comment(phase.label));

        if phase.spindle_rpm != current_rpm {
            let _ = writeln!(output, "M3 S{}", phase.spindle_rpm);
            current_rpm = phase.spindle_rpm;
        }

        for m in &phase.toolpath.moves {
            match m.move_type {
                MoveType::Rapid => {
                    output.push_str(&post.rapid(m.target.x, m.target.y, m.target.z));
                    last_feed = None;
                }
                MoveType::Linear { feed_rate } => {
                    if last_feed != Some(feed_rate) {
                        output.push_str(&post.linear(
                            m.target.x, m.target.y, m.target.z, feed_rate,
                        ));
                        last_feed = Some(feed_rate);
                    } else {
                        let dp = post.decimal_places();
                        let _ = writeln!(
                            output,
                            "G1 X{:.dp$} Y{:.dp$} Z{:.dp$}",
                            m.target.x, m.target.y, m.target.z
                        );
                    }
                }
                MoveType::ArcCW { i, j, feed_rate } => {
                    output.push_str(&post.arc_cw(
                        m.target.x, m.target.y, m.target.z, i, j, feed_rate,
                    ));
                    last_feed = Some(feed_rate);
                }
                MoveType::ArcCCW { i, j, feed_rate } => {
                    output.push_str(&post.arc_ccw(
                        m.target.x, m.target.y, m.target.z, i, j, feed_rate,
                    ));
                    last_feed = Some(feed_rate);
                }
            }
        }
    }

    output.push_str(&post.postamble());
    output
}

/// Replace G0 rapid moves with G1 at a high feedrate.
/// Used for machines with unpredictable rapid behavior (e.g., GRBL "dogleg" rapids).
pub fn replace_rapids_with_feed(gcode: &str, high_feedrate: f64) -> String {
    let mut output = String::with_capacity(gcode.len());
    for line in gcode.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("G0 ") || trimmed.starts_with("G0X") {
            // Replace G0 with G1 and append feedrate
            let rest = &trimmed[2..];
            output.push_str(&format!("G1{rest} F{high_feedrate:.1}\n"));
        } else {
            output.push_str(line);
            output.push('\n');
        }
    }
    output
}

/// Get a post-processor by name.
pub fn get_post_processor(name: &str) -> Option<Box<dyn PostProcessor>> {
    match name.to_lowercase().as_str() {
        "grbl" => Some(Box::new(GrblPost)),
        "linuxcnc" => Some(Box::new(LinuxCncPost)),
        "mach3" => Some(Box::new(Mach3Post)),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::geo::P3;
    use crate::toolpath::Toolpath;

    #[test]
    fn test_grbl_gcode() {
        let mut tp = Toolpath::new();
        tp.rapid_to(P3::new(0.0, 0.0, 10.0));
        tp.feed_to(P3::new(10.0, 0.0, 0.0), 1000.0);
        tp.feed_to(P3::new(20.0, 0.0, 0.0), 1000.0);

        let gcode = emit_gcode(&tp, &GrblPost, 18000);

        assert!(gcode.contains("G17 G21 G90"));
        assert!(gcode.contains("M3 S18000"));
        assert!(gcode.contains("G0 X0.000 Y0.000 Z10.000"));
        assert!(gcode.contains("G1 X10.000 Y0.000 Z0.000 F1000"));
        // Second G1 should omit F (modal)
        assert!(gcode.contains("G1 X20.000 Y0.000 Z0.000\n"));
        assert!(gcode.contains("M5"));
        assert!(gcode.contains("M30"));
    }

    #[test]
    fn test_mach3_gcode() {
        let mut tp = Toolpath::new();
        tp.rapid_to(P3::new(0.0, 0.0, 10.0));
        tp.feed_to(P3::new(10.0, 0.0, 0.0), 1000.0);

        let gcode = emit_gcode(&tp, &Mach3Post, 18000);

        assert!(gcode.contains("G17 G21 G90"));
        assert!(gcode.contains("G4 P2"), "Mach3 should have spindle dwell");
        assert!(gcode.contains("G28 G91 Z0"), "Mach3 should have G28 return");
        assert!(gcode.contains("M30"));
    }

    #[test]
    fn test_grbl_arc_gcode() {
        let mut tp = Toolpath::new();
        tp.rapid_to(P3::new(10.0, 0.0, -3.0));
        tp.arc_cw_to(P3::new(0.0, 10.0, -3.0), -10.0, 0.0, 1000.0);
        tp.arc_ccw_to(P3::new(-10.0, 0.0, -3.0), 0.0, 10.0, 1000.0);

        let gcode = emit_gcode(&tp, &GrblPost, 18000);

        assert!(gcode.contains("G2 X0.000 Y10.000 Z-3.000 I-10.000 J0.000 F1000"));
        assert!(gcode.contains("G3 X-10.000 Y0.000 Z-3.000 I0.000 J10.000 F1000"));
    }

    #[test]
    fn test_get_post_processor() {
        assert!(get_post_processor("grbl").is_some());
        assert!(get_post_processor("linuxcnc").is_some());
        assert!(get_post_processor("mach3").is_some());
        assert!(get_post_processor("unknown").is_none());
    }

    #[test]
    fn test_emit_gcode_phased_same_spindle() {
        let mut tp1 = Toolpath::new();
        tp1.rapid_to(P3::new(0.0, 0.0, 10.0));
        tp1.feed_to(P3::new(10.0, 0.0, 0.0), 1000.0);

        let mut tp2 = Toolpath::new();
        tp2.rapid_to(P3::new(20.0, 0.0, 10.0));
        tp2.feed_to(P3::new(30.0, 0.0, 0.0), 800.0);

        let phases = vec![
            GcodePhase { toolpath: &tp1, spindle_rpm: 18000, label: "Op 0 — pocket" },
            GcodePhase { toolpath: &tp2, spindle_rpm: 18000, label: "Op 1 — profile" },
        ];
        let gcode = emit_gcode_phased(&phases, &GrblPost);

        // Should have one preamble with M3 S18000
        assert!(gcode.contains("M3 S18000"));
        // Should have both operations' comments
        assert!(gcode.contains("(Op 0"));
        assert!(gcode.contains("(Op 1"));
        // No extra spindle speed change since both are 18000
        let m3_count = gcode.matches("M3 S").count();
        assert_eq!(m3_count, 1, "Same spindle speed should not emit extra M3");
    }

    #[test]
    fn test_emit_gcode_phased_different_spindle() {
        let mut tp1 = Toolpath::new();
        tp1.rapid_to(P3::new(0.0, 0.0, 10.0));
        tp1.feed_to(P3::new(10.0, 0.0, 0.0), 1000.0);

        let mut tp2 = Toolpath::new();
        tp2.rapid_to(P3::new(20.0, 0.0, 10.0));
        tp2.feed_to(P3::new(30.0, 0.0, 0.0), 800.0);

        let phases = vec![
            GcodePhase { toolpath: &tp1, spindle_rpm: 18000, label: "Op 0 — rough" },
            GcodePhase { toolpath: &tp2, spindle_rpm: 24000, label: "Op 1 — finish" },
        ];
        let gcode = emit_gcode_phased(&phases, &GrblPost);

        // Should have preamble M3 S18000 + later M3 S24000
        assert!(gcode.contains("M3 S18000"));
        assert!(gcode.contains("M3 S24000"));
        let m3_count = gcode.matches("M3 S").count();
        assert_eq!(m3_count, 2, "Different spindle speeds should emit M3 for each");
    }
}
