//! Render a `Program` IR to bytes using a data-driven `PostDefinition`.
//!
//! This is the Phase 3 successor to the per-impl `PostProcessor` trait:
//! a single emit function walks `Statement`s and formats each line with
//! the post's `Decimals`/`CommentStyle`/template strings. Move-line
//! shape (`G0 X{x} Y{y} Z{z}`, etc.) is identical across the three
//! shipped posts, so it is hard-coded here and parameterized by
//! `decimals.{xyz,feed,ijk}` rather than templated. Multi-line blocks
//! (preamble, postamble, program-pause) come from `PostDefinition`
//! templates with `{spindle_rpm}` / `{message_comment}` substitution.
//!
//! Byte-parity vs the legacy `PostProcessor` trait is enforced by the
//! `gcode_emitter_parity` integration test.

use std::fmt::Write;

use super::ir::{Program, Statement};
use super::post::PostDefinition;

/// Render a `Program` to g-code text using the given `PostDefinition`.
pub fn emit_program(program: &Program, post: &PostDefinition) -> String {
    let mut output = String::new();
    for statement in &program.statements {
        emit_statement(&mut output, statement, post);
    }
    output
}

fn emit_statement(output: &mut String, statement: &Statement, post: &PostDefinition) {
    let xyz = post.decimals.xyz;
    let feed_dp = post.decimals.feed;
    let ijk = post.decimals.ijk;

    match *statement {
        Statement::Preamble { spindle_rpm } => {
            output.push_str(&post.render_preamble(spindle_rpm));
        }
        Statement::Postamble => output.push_str(&post.render_postamble()),
        Statement::ProgramPause { ref message } => {
            output.push_str(&post.render_program_pause(message));
        }
        Statement::Comment(ref text) => output.push_str(&post.render_comment(text)),
        Statement::Raw(ref text) => output.push_str(text),
        Statement::Rapid { x, y, z } => {
            let _ = writeln!(output, "G0 X{x:.xyz$} Y{y:.xyz$} Z{z:.xyz$}");
        }
        Statement::Linear { x, y, z, feed } => {
            let _ = writeln!(
                output,
                "G1 X{x:.xyz$} Y{y:.xyz$} Z{z:.xyz$} F{feed:.feed_dp$}"
            );
        }
        Statement::LinearModal { x, y, z } => {
            let _ = writeln!(output, "G1 X{x:.xyz$} Y{y:.xyz$} Z{z:.xyz$}");
        }
        Statement::ArcCw { x, y, z, i, j, feed } => {
            let _ = writeln!(
                output,
                "G2 X{x:.xyz$} Y{y:.xyz$} Z{z:.xyz$} I{i:.ijk$} J{j:.ijk$} F{feed:.feed_dp$}"
            );
        }
        Statement::ArcCcw { x, y, z, i, j, feed } => {
            let _ = writeln!(
                output,
                "G3 X{x:.xyz$} Y{y:.xyz$} Z{z:.xyz$} I{i:.ijk$} J{j:.ijk$} F{feed:.feed_dp$}"
            );
        }
        Statement::SafeZRetract { z } => {
            let _ = writeln!(output, "G0 Z{z:.xyz$}");
        }
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;
    use crate::gcode::post;
    use crate::gcode::program_builder;
    use crate::geo::P3;
    use crate::toolpath::Toolpath;

    #[test]
    fn emit_basic_grbl_lines() {
        let mut tp = Toolpath::new();
        tp.rapid_to(P3::new(0.0, 0.0, 10.0));
        tp.feed_to(P3::new(10.0, 0.0, 0.0), 1000.0);
        tp.feed_to(P3::new(20.0, 0.0, 0.0), 1000.0);

        let program = program_builder::build_single(&tp, 18_000);
        let gcode = emit_program(&program, post::grbl());

        assert!(gcode.contains("(Generated by rs_cam)"));
        assert!(gcode.contains("M3 S18000"));
        assert!(gcode.contains("G0 X0.000 Y0.000 Z10.000"));
        assert!(gcode.contains("G1 X10.000 Y0.000 Z0.000 F1000"));
        // Modal F-elision on second linear at the same feed.
        assert!(gcode.contains("G1 X20.000 Y0.000 Z0.000\n"));
        assert!(gcode.contains("M30"));
    }

    #[test]
    fn emit_linuxcnc_uses_4_decimals_and_g54() {
        let mut tp = Toolpath::new();
        tp.rapid_to(P3::new(1.234567, 0.0, 5.0));
        tp.feed_to(P3::new(1.234567, 1.0, -2.0), 600.0);

        let program = program_builder::build_single(&tp, 18_000);
        let gcode = emit_program(&program, post::linuxcnc());

        assert!(gcode.contains("G54"));
        assert!(gcode.contains("G0 X1.2346 Y0.0000 Z5.0000"));
        assert!(gcode.contains("F600.0"));
        assert!(gcode.contains("G53 G0 Z0"));
        assert!(gcode.contains("M2"));
    }

    #[test]
    fn emit_mach3_dwells_after_spindle() {
        let mut tp = Toolpath::new();
        tp.rapid_to(P3::new(0.0, 0.0, 10.0));

        let program = program_builder::build_single(&tp, 18_000);
        let gcode = emit_program(&program, post::mach3());

        assert!(gcode.contains("G4 P2"));
        assert!(gcode.contains("G28 G91 Z0"));
    }
}
