//! G-code generation and post-processors.
//!
//! Note: `let _ = write!(...)` is used throughout this module for writing to `String`.
//! Writing to `String` is infallible (only fails on OOM, which panics regardless),
//! so discarding the `Result` with `let _ =` is safe.

pub mod ir;
mod modal;
pub mod program_builder;

pub use ir::{Program, ProgramMetadata, Statement};

use crate::compute::catalog::effective_spindle_rpm;
use crate::session::ProjectSession;
use crate::simulation_cut::SimulationCutTrace;
use crate::toolpath::{MoveType, Toolpath};
use serde::{Deserialize, Serialize};
use std::fmt::{Display, Write};

/// Policy knobs reserved for tool-load-aware export checks.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct ToolLoadExportPolicy {
    pub accept_unmodeled: bool,
    pub accept_exceeded: bool,
}

/// Error returned by checked G-code export.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExportError {
    message: String,
}

impl ExportError {
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

impl Display for ExportError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.message)
    }
}

impl std::error::Error for ExportError {}

/// Direction for G41/G42 controller cutter compensation.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ControllerCompensation {
    /// G41 — cutter compensation left.
    Left,
    /// G42 — cutter compensation right.
    Right,
}

/// Coolant mode for G-code output.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CoolantMode {
    /// No coolant (default).
    #[default]
    Off,
    /// Mist coolant (M7).
    Mist,
    /// Flood coolant (M8).
    Flood,
    /// Both mist and flood (M7 + M8).
    Both,
}

impl CoolantMode {
    /// Emit the G-code command(s) to activate this coolant mode.
    /// Returns an empty string for `Off`.
    pub fn start_gcode(self) -> &'static str {
        match self {
            CoolantMode::Off => "",
            CoolantMode::Mist => "M7\n",
            CoolantMode::Flood => "M8\n",
            CoolantMode::Both => "M7\nM8\n",
        }
    }

    /// Returns true if coolant is active (not Off).
    pub fn is_active(self) -> bool {
        self != CoolantMode::Off
    }
}

/// Post-processor trait for machine-specific G-code dialects.
pub trait PostProcessor {
    fn name(&self) -> &str;
    fn preamble(&self, spindle_rpm: u32) -> String;
    fn postamble(&self) -> String;
    fn rapid(&self, x: f64, y: f64, z: f64) -> String;
    fn linear(&self, x: f64, y: f64, z: f64, feed: f64) -> String;
    fn arc_cw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String;
    fn arc_ccw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String;
    fn comment(&self, text: &str) -> String;
    fn decimal_places(&self) -> usize {
        3
    }

    /// Program pause for setup changes (M0). Override for machine-specific behavior.
    fn program_pause(&self, message: &str) -> String {
        let mut s = String::new();
        let _ = writeln!(s, "M5");
        s.push_str(&self.comment(message));
        let _ = writeln!(s, "M0");
        s
    }

    // Canned drilling cycles (default implementations)
    fn drill_simple(&self, x: f64, y: f64, z: f64, r: f64, feed: f64) -> String {
        format!("G81 X{x:.4} Y{y:.4} Z{z:.4} R{r:.4} F{feed:.1}\n")
    }
    fn drill_dwell(&self, x: f64, y: f64, z: f64, r: f64, feed: f64, dwell: f64) -> String {
        format!("G82 X{x:.4} Y{y:.4} Z{z:.4} R{r:.4} P{dwell:.3} F{feed:.1}\n")
    }
    fn drill_peck(&self, x: f64, y: f64, z: f64, r: f64, feed: f64, peck: f64) -> String {
        format!("G83 X{x:.4} Y{y:.4} Z{z:.4} R{r:.4} Q{peck:.4} F{feed:.1}\n")
    }
    fn drill_chip_break(&self, x: f64, y: f64, z: f64, r: f64, feed: f64, peck: f64) -> String {
        format!("G73 X{x:.4} Y{y:.4} Z{z:.4} R{r:.4} Q{peck:.4} F{feed:.1}\n")
    }
    fn drill_cancel(&self) -> String {
        "G80\n".to_owned()
    }
}

/// GRBL-compatible post-processor.
pub struct GrblPost;

impl PostProcessor for GrblPost {
    fn name(&self) -> &str {
        "GRBL"
    }

    fn preamble(&self, spindle_rpm: u32) -> String {
        let mut s = String::new();
        let _ = writeln!(s, "(Generated by rs_cam)");
        let _ = writeln!(s, "G17 G21 G90 G40 G49 G80");
        let _ = writeln!(s, "M3 S{spindle_rpm}");
        s
    }

    fn postamble(&self) -> String {
        let mut s = String::new();
        let _ = writeln!(s, "M5");
        let _ = writeln!(s, "G0 Z10.000");
        let _ = writeln!(s, "M30");
        s
    }

    fn rapid(&self, x: f64, y: f64, z: f64) -> String {
        format!("G0 X{x:.3} Y{y:.3} Z{z:.3}\n")
    }

    fn linear(&self, x: f64, y: f64, z: f64, feed: f64) -> String {
        format!("G1 X{x:.3} Y{y:.3} Z{z:.3} F{feed:.0}\n")
    }

    fn arc_cw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String {
        format!("G2 X{x:.3} Y{y:.3} Z{z:.3} I{i:.3} J{j:.3} F{feed:.0}\n")
    }

    fn arc_ccw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String {
        format!("G3 X{x:.3} Y{y:.3} Z{z:.3} I{i:.3} J{j:.3} F{feed:.0}\n")
    }

    fn comment(&self, text: &str) -> String {
        format!("({text})\n")
    }
}

/// LinuxCNC-compatible post-processor.
pub struct LinuxCncPost;

impl PostProcessor for LinuxCncPost {
    fn name(&self) -> &str {
        "LinuxCNC"
    }

    fn preamble(&self, spindle_rpm: u32) -> String {
        let mut s = String::new();
        let _ = writeln!(s, "(Generated by rs_cam)");
        let _ = writeln!(s, "G17 G21 G90 G40 G49 G80");
        let _ = writeln!(s, "G54");
        let _ = writeln!(s, "M3 S{spindle_rpm}");
        s
    }

    fn postamble(&self) -> String {
        let mut s = String::new();
        let _ = writeln!(s, "M5");
        let _ = writeln!(s, "G53 G0 Z0");
        let _ = writeln!(s, "M2");
        s
    }

    fn rapid(&self, x: f64, y: f64, z: f64) -> String {
        format!("G0 X{x:.4} Y{y:.4} Z{z:.4}\n")
    }

    fn linear(&self, x: f64, y: f64, z: f64, feed: f64) -> String {
        format!("G1 X{x:.4} Y{y:.4} Z{z:.4} F{feed:.1}\n")
    }

    fn arc_cw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String {
        format!("G2 X{x:.4} Y{y:.4} Z{z:.4} I{i:.4} J{j:.4} F{feed:.1}\n")
    }

    fn arc_ccw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String {
        format!("G3 X{x:.4} Y{y:.4} Z{z:.4} I{i:.4} J{j:.4} F{feed:.1}\n")
    }

    fn comment(&self, text: &str) -> String {
        format!("({text})\n")
    }

    fn decimal_places(&self) -> usize {
        4
    }
}

/// Emit G-code from a toolpath using the given post-processor.
pub fn emit_gcode(toolpath: &Toolpath, post: &dyn PostProcessor, spindle_rpm: u32) -> String {
    let mut output = String::new();

    output.push_str(&post.preamble(spindle_rpm));

    let mut last_feed: Option<f64> = None;

    for m in &toolpath.moves {
        match m.move_type {
            MoveType::Rapid => {
                output.push_str(&post.rapid(m.target.x, m.target.y, m.target.z));
                last_feed = None;
            }
            MoveType::Linear { feed_rate } => {
                if last_feed != Some(feed_rate) {
                    output.push_str(&post.linear(m.target.x, m.target.y, m.target.z, feed_rate));
                    last_feed = Some(feed_rate);
                } else {
                    let dp = post.decimal_places();
                    let _ = writeln!(
                        output,
                        "G1 X{:.dp$} Y{:.dp$} Z{:.dp$}",
                        m.target.x, m.target.y, m.target.z
                    );
                }
            }
            MoveType::ArcCW { i, j, feed_rate } => {
                output.push_str(&post.arc_cw(m.target.x, m.target.y, m.target.z, i, j, feed_rate));
                last_feed = Some(feed_rate);
            }
            MoveType::ArcCCW { i, j, feed_rate } => {
                output.push_str(&post.arc_ccw(m.target.x, m.target.y, m.target.z, i, j, feed_rate));
                last_feed = Some(feed_rate);
            }
        }
    }

    output.push_str(&post.postamble());
    output
}

/// Mach3-compatible post-processor.
pub struct Mach3Post;

impl PostProcessor for Mach3Post {
    fn name(&self) -> &str {
        "Mach3"
    }

    fn preamble(&self, spindle_rpm: u32) -> String {
        let mut s = String::new();
        let _ = writeln!(s, "(Generated by rs_cam)");
        let _ = writeln!(s, "G17 G21 G90 G40 G80");
        let _ = writeln!(s, "M3 S{spindle_rpm}");
        let _ = writeln!(s, "G4 P2"); // dwell for spindle spin-up
        s
    }

    fn postamble(&self) -> String {
        let mut s = String::new();
        let _ = writeln!(s, "M5");
        let _ = writeln!(s, "G0 Z10.000");
        let _ = writeln!(s, "G28 G91 Z0");
        let _ = writeln!(s, "M30");
        s
    }

    fn rapid(&self, x: f64, y: f64, z: f64) -> String {
        format!("G0 X{x:.4} Y{y:.4} Z{z:.4}\n")
    }

    fn linear(&self, x: f64, y: f64, z: f64, feed: f64) -> String {
        format!("G1 X{x:.4} Y{y:.4} Z{z:.4} F{feed:.1}\n")
    }

    fn arc_cw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String {
        format!("G2 X{x:.4} Y{y:.4} Z{z:.4} I{i:.4} J{j:.4} F{feed:.1}\n")
    }

    fn arc_ccw(&self, x: f64, y: f64, z: f64, i: f64, j: f64, feed: f64) -> String {
        format!("G3 X{x:.4} Y{y:.4} Z{z:.4} I{i:.4} J{j:.4} F{feed:.1}\n")
    }

    fn comment(&self, text: &str) -> String {
        format!("({text})\n")
    }

    fn decimal_places(&self) -> usize {
        4
    }
}

/// A phase in a multi-operation job: toolpath + spindle speed + label.
pub struct GcodePhase<'a> {
    pub toolpath: &'a Toolpath,
    pub spindle_rpm: u32,
    pub label: &'a str,
    /// Raw G-code to emit before this toolpath's moves (user-defined).
    pub pre_gcode: Option<&'a str>,
    /// Raw G-code to emit after this toolpath's moves (user-defined).
    pub post_gcode: Option<&'a str>,
    /// Tool number for M6 tool change. If `Some` and different from previous phase,
    /// an M6 T{n} command is emitted before this phase.
    pub tool_number: Option<u32>,
    /// Coolant mode for this phase. Coolant on/off commands are emitted
    /// when the mode changes between phases.
    pub coolant: CoolantMode,
    /// Controller cutter compensation (G41/G42). When `Some`, a G41/G42
    /// command is emitted before the first cutting move and G40 after the last.
    pub controller_compensation: Option<ControllerCompensation>,
}

/// Emit G-code from multiple phases, inserting tool changes, spindle speed
/// changes, and coolant commands between operations as needed.
pub(crate) fn emit_gcode_phased(phases: &[GcodePhase<'_>], post: &dyn PostProcessor) -> String {
    if phases.is_empty() {
        return String::new();
    }

    let mut output = String::new();
    // SAFETY: early return above guarantees phases is non-empty
    #[allow(clippy::indexing_slicing)]
    let first_phase = &phases[0];
    let first_rpm = first_phase.spindle_rpm;
    output.push_str(&post.preamble(first_rpm));

    // Emit coolant start if the first phase has coolant enabled
    let first_coolant = first_phase.coolant;
    if first_coolant.is_active() {
        output.push_str(first_coolant.start_gcode());
    }

    let mut current_rpm = first_rpm;
    let mut current_tool: Option<u32> = first_phase.tool_number;
    let mut current_coolant = first_coolant;
    let mut last_feed: Option<f64> = None;

    for (idx, phase) in phases.iter().enumerate() {
        output.push_str(&post.comment(phase.label));

        // Tool change: emit M6 T{n} if tool number changed
        if idx > 0
            && let Some(tool_num) = phase.tool_number
            && current_tool != Some(tool_num)
        {
            // Stop spindle and coolant before tool change
            if current_coolant.is_active() {
                let _ = writeln!(output, "M9");
            }
            let _ = writeln!(output, "M5");
            let _ = writeln!(output, "M6 T{tool_num}");
            // Restart spindle after tool change
            let _ = writeln!(output, "M3 S{}", phase.spindle_rpm);
            current_rpm = phase.spindle_rpm;
            current_tool = Some(tool_num);
            // Restart coolant after tool change if needed
            if phase.coolant.is_active() {
                output.push_str(phase.coolant.start_gcode());
            }
            current_coolant = phase.coolant;
            last_feed = None;
        }

        // Spindle speed change (only if we didn't already emit it in the tool change block)
        if phase.spindle_rpm != current_rpm {
            let _ = writeln!(output, "M3 S{}", phase.spindle_rpm);
            current_rpm = phase.spindle_rpm;
        }

        // Coolant mode change (only if we didn't already handle it in tool change)
        if idx > 0
            && phase.coolant != current_coolant
            && !(phase.tool_number.is_some() && current_tool == phase.tool_number)
        {
            if current_coolant.is_active() && !phase.coolant.is_active() {
                let _ = writeln!(output, "M9");
            } else if phase.coolant.is_active() {
                if current_coolant.is_active() {
                    let _ = writeln!(output, "M9");
                }
                output.push_str(phase.coolant.start_gcode());
            }
            current_coolant = phase.coolant;
        }

        if let Some(pre) = phase.pre_gcode
            && !pre.is_empty()
        {
            output.push_str(pre);
            if !pre.ends_with('\n') {
                output.push('\n');
            }
        }

        // Controller compensation: emit G41/G42 before first cutting move
        let comp = phase.controller_compensation;
        let mut comp_started = false;
        let tool_num_for_comp = phase.tool_number.unwrap_or(1);

        for m in &phase.toolpath.moves {
            match m.move_type {
                MoveType::Rapid => {
                    output.push_str(&post.rapid(m.target.x, m.target.y, m.target.z));
                    last_feed = None;
                }
                MoveType::Linear { feed_rate } => {
                    if let Some(dir) = comp
                        && !comp_started
                    {
                        let code = match dir {
                            ControllerCompensation::Left => "G41",
                            ControllerCompensation::Right => "G42",
                        };
                        let _ = writeln!(output, "{code} D{tool_num_for_comp}");
                        comp_started = true;
                    }
                    if last_feed != Some(feed_rate) {
                        output
                            .push_str(&post.linear(m.target.x, m.target.y, m.target.z, feed_rate));
                        last_feed = Some(feed_rate);
                    } else {
                        let dp = post.decimal_places();
                        let _ = writeln!(
                            output,
                            "G1 X{:.dp$} Y{:.dp$} Z{:.dp$}",
                            m.target.x, m.target.y, m.target.z
                        );
                    }
                }
                MoveType::ArcCW { i, j, feed_rate } => {
                    if let Some(dir) = comp
                        && !comp_started
                    {
                        let code = match dir {
                            ControllerCompensation::Left => "G41",
                            ControllerCompensation::Right => "G42",
                        };
                        let _ = writeln!(output, "{code} D{tool_num_for_comp}");
                        comp_started = true;
                    }
                    output.push_str(
                        &post.arc_cw(m.target.x, m.target.y, m.target.z, i, j, feed_rate),
                    );
                    last_feed = Some(feed_rate);
                }
                MoveType::ArcCCW { i, j, feed_rate } => {
                    if let Some(dir) = comp
                        && !comp_started
                    {
                        let code = match dir {
                            ControllerCompensation::Left => "G41",
                            ControllerCompensation::Right => "G42",
                        };
                        let _ = writeln!(output, "{code} D{tool_num_for_comp}");
                        comp_started = true;
                    }
                    output.push_str(
                        &post.arc_ccw(m.target.x, m.target.y, m.target.z, i, j, feed_rate),
                    );
                    last_feed = Some(feed_rate);
                }
            }
        }

        // Cancel controller compensation after the last cutting move
        if comp_started {
            let _ = writeln!(output, "G40");
        }

        if let Some(post_gc) = phase.post_gcode
            && !post_gc.is_empty()
        {
            output.push_str(post_gc);
            if !post_gc.ends_with('\n') {
                output.push('\n');
            }
        }
    }

    // Turn off coolant before postamble if it was active
    if current_coolant.is_active() {
        let _ = writeln!(output, "M9");
    }

    output.push_str(&post.postamble());
    output
}

/// Emit checked G-code from a project session.
pub fn export_gcode_checked(
    project: &ProjectSession,
    sim_trace: Option<&SimulationCutTrace>,
    policy: ToolLoadExportPolicy,
) -> Result<String, ExportError> {
    // Run the project-level tool-load report and gate on policy. Phase 1a
    // ships the deflection criterion (purely geometric L/D); chipload and
    // power are stubs returning `Unmodeled(NotImplemented)` and are therefore
    // gated behind `policy.accept_unmodeled`.
    let report = project_load_report(project, sim_trace);
    enforce_load_policy(&report, &policy)?;

    let post_format = match project.post_config().format.to_ascii_lowercase().as_str() {
        "linuxcnc" | "linux_cnc" => PostFormat::LinuxCnc,
        "mach3" => PostFormat::Mach3,
        _ => PostFormat::Grbl,
    };
    let post = post_format.post_processor();

    let phases: Vec<GcodePhase<'_>> = project
        .toolpath_configs()
        .iter()
        .enumerate()
        .filter_map(|(idx, tc)| {
            let result = project.get_result(idx)?;
            Some(GcodePhase {
                toolpath: result.toolpath(),
                spindle_rpm: effective_spindle_rpm(
                    &tc.operation,
                    project.post_config().spindle_speed,
                ),
                label: &tc.name,
                tool_number: None,
                coolant: CoolantMode::Off,
                pre_gcode: tc.pre_gcode.as_deref(),
                post_gcode: tc.post_gcode.as_deref(),
                controller_compensation: controller_comp_for_project_toolpath(tc),
            })
        })
        .collect();

    // Phase-level checked emit is currently a no-op enforcer (the project
    // gate above is the source of truth); pass policy through unchanged.
    export_gcode_phases_checked(&phases, post.as_ref(), sim_trace, policy)
}

/// Build a `ToolLoadReport` from a `ProjectSession`. Phase 1a wires
/// `chipload` (per-sample vs vendor LUT, requires `sim_trace`) and
/// `deflection` (geometric L/D, sample-independent). The `power`
/// criterion is stubbed `Unmodeled(NotImplemented)` until Phase 1b's
/// arc-engagement-driven power calc lands.
pub fn project_load_report(
    project: &ProjectSession,
    sim_trace: Option<&SimulationCutTrace>,
) -> crate::tool_load::ToolLoadReport {
    use crate::feeds::vendor_lut::{LutOperationFamily, LutPassRole};
    use crate::feeds::{OperationFamily, PassRole};

    let material = &project.stock_config().material;
    let mut per_toolpath = Vec::new();
    for tc in project.toolpath_configs() {
        if !tc.enabled {
            continue;
        }
        let Some(tool_cfg) = project.get_tool(crate::compute::tool_config::ToolId(tc.tool_id))
        else {
            // Toolpath references a tool that's been removed — skip rather
            // than fabricate a verdict.
            continue;
        };
        let tool_def = crate::compute::cutter::build_cutter(tool_cfg);
        let spec = tc.operation.spec();
        let lut_op = match spec.feeds_family {
            OperationFamily::Adaptive => LutOperationFamily::Adaptive,
            OperationFamily::Pocket => LutOperationFamily::Pocket,
            OperationFamily::Contour => LutOperationFamily::Contour,
            OperationFamily::Parallel => LutOperationFamily::Parallel,
            OperationFamily::Scallop => LutOperationFamily::Scallop,
            OperationFamily::Trace => LutOperationFamily::Trace,
            OperationFamily::Face => LutOperationFamily::Face,
        };
        let lut_pass = match spec.feeds_pass_role {
            PassRole::Roughing => LutPassRole::Roughing,
            PassRole::SemiFinish => LutPassRole::SemiFinish,
            PassRole::Finish => LutPassRole::Finish,
        };
        let machine = project.machine();
        // Item C: pass the operation's commanded feed rate so the
        // chipload guardrail can filter out transient (plunge/ramp/entry)
        // samples and only measure steady-state cutting against the LUT.
        let operation_feed_rate_mm_min = tc.operation.feed_rate();
        // gcode export keeps strict LUT/machine-ceiling behaviour — only
        // the optimizer routes wider tolerance bands. See `ToleranceBands`.
        let strict_tolerance = crate::tool_load::ToleranceBands::default();
        per_toolpath.push(crate::tool_load::ToolpathLoadVerdict {
            toolpath_id: tc.id,
            chipload: crate::tool_load::chipload::evaluate(
                tc.id,
                &tool_def,
                material,
                sim_trace,
                lut_op,
                lut_pass,
                operation_feed_rate_mm_min,
                tc.operation.op_type(),
                &strict_tolerance,
            ),
            power: crate::tool_load::power::evaluate(
                tc.id,
                &tool_def,
                material,
                machine,
                sim_trace,
                &strict_tolerance,
            ),
            deflection: crate::tool_load::deflection::evaluate(
                tc.id,
                &tool_def,
                material,
                sim_trace,
                &strict_tolerance,
            ),
        });
    }
    crate::tool_load::ToolLoadReport { per_toolpath }
}

/// Enforce a `ToolLoadExportPolicy` against a report. Returns a structured
/// error message naming each offending toolpath and criterion so the user
/// (or UI) sees exactly what to override.
pub fn enforce_load_policy(
    report: &crate::tool_load::ToolLoadReport,
    policy: &ToolLoadExportPolicy,
) -> Result<(), ExportError> {
    if !policy.accept_exceeded {
        let exceeded = report.exceeded_criteria();
        if !exceeded.is_empty() {
            let mut msg =
                String::from("G-code export refused: tool load exceeded on toolpath(s):\n");
            for (id, crits) in &exceeded {
                let reason_list: Vec<String> = crits
                    .iter()
                    .map(|ec| format!("{}={}", ec.label, ec.reason_label))
                    .collect();
                let _ = writeln!(msg, "  toolpath {id}: {}", reason_list.join(", "));
            }
            msg.push_str(
                "Pass `accept_exceeded=true` to override (this is a known-dangerous override).",
            );
            return Err(ExportError::new(msg));
        }
    }
    if !policy.accept_unmodeled && report.any_unmodeled() {
        let mut msg =
            String::from("G-code export refused: tool load not fully modeled for toolpath(s):\n");
        for v in &report.per_toolpath {
            if v.any_unmodeled() {
                let mut crits = Vec::new();
                if let crate::tool_load::ChiploadVerdict::Unmodeled { reason } = &v.chipload {
                    crits.push(format!("chipload={reason:?}"));
                }
                if let crate::tool_load::PowerVerdict::Unmodeled { reason } = &v.power {
                    crits.push(format!("power={reason:?}"));
                }
                if let crate::tool_load::DeflectionVerdict::Unmodeled { reason } = &v.deflection {
                    crits.push(format!("deflection={reason:?}"));
                }
                let _ = writeln!(msg, "  toolpath {}: {}", v.toolpath_id, crits.join(", "));
            }
        }
        msg.push_str("Pass `accept_unmodeled=true` to acknowledge unmodeled criteria.");
        return Err(ExportError::new(msg));
    }
    Ok(())
}

/// Emit checked G-code from pre-built phases.
pub fn export_gcode_phases_checked(
    phases: &[GcodePhase<'_>],
    post: &dyn PostProcessor,
    _sim_trace: Option<&SimulationCutTrace>,
    _policy: ToolLoadExportPolicy,
) -> Result<String, ExportError> {
    // TODO: enforced in tool_load follow-up. The policy and simulation trace
    // are intentionally accepted but ignored in this refactor.
    Ok(emit_gcode_phased(phases, post))
}

fn controller_comp_for_project_toolpath(
    tc: &crate::session::ToolpathConfig,
) -> Option<ControllerCompensation> {
    use crate::compute::{CompensationType, OperationConfig};
    use crate::profile::ProfileSide;

    if let OperationConfig::Profile(ref cfg) = tc.operation
        && cfg.compensation == CompensationType::InControl
    {
        return Some(match (cfg.side, cfg.climb) {
            (ProfileSide::Outside, true) => ControllerCompensation::Right,
            (ProfileSide::Outside, false) => ControllerCompensation::Left,
            (ProfileSide::Inside, true) => ControllerCompensation::Left,
            (ProfileSide::Inside, false) => ControllerCompensation::Right,
        });
    }
    None
}

/// A group of toolpath phases belonging to one setup.
pub struct GcodeSetupPhase<'a> {
    pub setup_label: &'a str,
    pub phases: Vec<GcodePhase<'a>>,
}

/// Emit checked G-code for multiple setups with M0 pauses between them.
pub fn export_gcode_multi_setup_checked(
    setups: &[GcodeSetupPhase<'_>],
    post: &dyn PostProcessor,
    safe_z: f64,
    _sim_trace: Option<&SimulationCutTrace>,
    _policy: ToolLoadExportPolicy,
) -> Result<String, ExportError> {
    // TODO: enforced in tool_load follow-up. The policy and simulation trace
    // are intentionally accepted but ignored in this refactor.
    Ok(emit_gcode_multi_setup(setups, post, safe_z))
}

/// Emit G-code for multiple setups with M0 pauses between them.
pub(crate) fn emit_gcode_multi_setup(
    setups: &[GcodeSetupPhase<'_>],
    post: &dyn PostProcessor,
    safe_z: f64,
) -> String {
    if setups.is_empty() {
        return String::new();
    }

    let mut output = String::new();
    let first_rpm = setups
        .iter()
        .flat_map(|setup| setup.phases.iter())
        .map(|phase| phase.spindle_rpm)
        .next()
        .unwrap_or(18_000);

    output.push_str(&post.preamble(first_rpm));

    let first_coolant = setups
        .iter()
        .flat_map(|setup| setup.phases.iter())
        .map(|phase| phase.coolant)
        .next()
        .unwrap_or(CoolantMode::Off);
    if first_coolant.is_active() {
        output.push_str(first_coolant.start_gcode());
    }

    let mut current_rpm = first_rpm;
    let mut current_tool: Option<u32> = setups
        .iter()
        .flat_map(|setup| setup.phases.iter())
        .find_map(|phase| phase.tool_number);
    let mut current_coolant = first_coolant;
    let mut last_feed: Option<f64> = None;
    let dp = post.decimal_places();

    for (setup_index, setup) in setups.iter().enumerate() {
        if setup_index > 0 {
            if current_coolant.is_active() {
                let _ = writeln!(output, "M9");
            }
            let _ = writeln!(output, "G0 Z{safe_z:.dp$}");
            output.push_str(&post.program_pause(&format!("Setup change: {}", setup.setup_label)));

            let next_rpm = setup
                .phases
                .first()
                .map(|phase| phase.spindle_rpm)
                .unwrap_or(current_rpm);
            let _ = writeln!(output, "M3 S{next_rpm}");
            current_rpm = next_rpm;
            last_feed = None;

            // Restart coolant for the first phase of this setup
            let next_coolant = setup
                .phases
                .first()
                .map(|phase| phase.coolant)
                .unwrap_or(CoolantMode::Off);
            if next_coolant.is_active() {
                output.push_str(next_coolant.start_gcode());
            }
            current_coolant = next_coolant;
        }

        output.push_str(&post.comment(&format!("=== {} ===", setup.setup_label)));

        for phase in &setup.phases {
            output.push_str(&post.comment(phase.label));

            // Tool change
            if let Some(tool_num) = phase.tool_number
                && current_tool != Some(tool_num)
            {
                if current_coolant.is_active() {
                    let _ = writeln!(output, "M9");
                }
                let _ = writeln!(output, "M5");
                let _ = writeln!(output, "M6 T{tool_num}");
                let _ = writeln!(output, "M3 S{}", phase.spindle_rpm);
                current_rpm = phase.spindle_rpm;
                current_tool = Some(tool_num);
                if phase.coolant.is_active() {
                    output.push_str(phase.coolant.start_gcode());
                }
                current_coolant = phase.coolant;
                last_feed = None;
            }

            if phase.spindle_rpm != current_rpm {
                let _ = writeln!(output, "M3 S{}", phase.spindle_rpm);
                current_rpm = phase.spindle_rpm;
            }

            // Coolant mode change
            if phase.coolant != current_coolant
                && !(phase.tool_number.is_some() && current_tool == phase.tool_number)
            {
                if current_coolant.is_active() && !phase.coolant.is_active() {
                    let _ = writeln!(output, "M9");
                } else if phase.coolant.is_active() {
                    if current_coolant.is_active() {
                        let _ = writeln!(output, "M9");
                    }
                    output.push_str(phase.coolant.start_gcode());
                }
                current_coolant = phase.coolant;
            }

            if let Some(pre) = phase.pre_gcode
                && !pre.is_empty()
            {
                output.push_str(pre);
                if !pre.ends_with('\n') {
                    output.push('\n');
                }
            }

            // Controller compensation: emit G41/G42 before first cutting move
            let comp = phase.controller_compensation;
            let mut comp_started = false;
            let tool_num_for_comp = phase.tool_number.unwrap_or(1);

            for m in &phase.toolpath.moves {
                match m.move_type {
                    MoveType::Rapid => {
                        output.push_str(&post.rapid(m.target.x, m.target.y, m.target.z));
                        last_feed = None;
                    }
                    MoveType::Linear { feed_rate } => {
                        if let Some(dir) = comp
                            && !comp_started
                        {
                            let code = match dir {
                                ControllerCompensation::Left => "G41",
                                ControllerCompensation::Right => "G42",
                            };
                            let _ = writeln!(output, "{code} D{tool_num_for_comp}");
                            comp_started = true;
                        }
                        if last_feed != Some(feed_rate) {
                            output.push_str(
                                &post.linear(m.target.x, m.target.y, m.target.z, feed_rate),
                            );
                            last_feed = Some(feed_rate);
                        } else {
                            let _ = writeln!(
                                output,
                                "G1 X{:.dp$} Y{:.dp$} Z{:.dp$}",
                                m.target.x, m.target.y, m.target.z
                            );
                        }
                    }
                    MoveType::ArcCW { i, j, feed_rate } => {
                        if let Some(dir) = comp
                            && !comp_started
                        {
                            let code = match dir {
                                ControllerCompensation::Left => "G41",
                                ControllerCompensation::Right => "G42",
                            };
                            let _ = writeln!(output, "{code} D{tool_num_for_comp}");
                            comp_started = true;
                        }
                        output.push_str(
                            &post.arc_cw(m.target.x, m.target.y, m.target.z, i, j, feed_rate),
                        );
                        last_feed = Some(feed_rate);
                    }
                    MoveType::ArcCCW { i, j, feed_rate } => {
                        if let Some(dir) = comp
                            && !comp_started
                        {
                            let code = match dir {
                                ControllerCompensation::Left => "G41",
                                ControllerCompensation::Right => "G42",
                            };
                            let _ = writeln!(output, "{code} D{tool_num_for_comp}");
                            comp_started = true;
                        }
                        output.push_str(
                            &post.arc_ccw(m.target.x, m.target.y, m.target.z, i, j, feed_rate),
                        );
                        last_feed = Some(feed_rate);
                    }
                }
            }

            // Cancel controller compensation after the last cutting move
            if comp_started {
                let _ = writeln!(output, "G40");
            }

            if let Some(post_gc) = phase.post_gcode
                && !post_gc.is_empty()
            {
                output.push_str(post_gc);
                if !post_gc.ends_with('\n') {
                    output.push('\n');
                }
            }
        }
    }

    // Turn off coolant before postamble if it was active
    if current_coolant.is_active() {
        let _ = writeln!(output, "M9");
    }

    output.push_str(&post.postamble());
    output
}

/// Replace G0 rapid moves with G1 at a high feedrate.
/// Used for machines with unpredictable rapid behavior (e.g., GRBL "dogleg" rapids).
pub fn replace_rapids_with_feed(gcode: &str, high_feedrate: f64) -> String {
    let mut output = String::with_capacity(gcode.len());
    for line in gcode.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("G0 ") || trimmed.starts_with("G0X") {
            // Replace G0 with G1 and append feedrate
            let rest = &trimmed[2..];
            output.push_str(&format!("G1{rest} F{high_feedrate:.1}\n"));
        } else {
            output.push_str(line);
            output.push('\n');
        }
    }
    output
}

/// Post-processor format selector.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PostFormat {
    Grbl,
    LinuxCnc,
    Mach3,
}

impl PostFormat {
    /// All available post-processor formats.
    pub const ALL: &[PostFormat] = &[PostFormat::Grbl, PostFormat::LinuxCnc, PostFormat::Mach3];

    /// Human-readable display label for UI.
    pub fn label(self) -> &'static str {
        match self {
            PostFormat::Grbl => "GRBL",
            PostFormat::LinuxCnc => "LinuxCNC",
            PostFormat::Mach3 => "Mach3",
        }
    }

    /// Create the corresponding post-processor instance.
    pub fn post_processor(self) -> Box<dyn PostProcessor> {
        match self {
            PostFormat::Grbl => Box::new(GrblPost),
            PostFormat::LinuxCnc => Box::new(LinuxCncPost),
            PostFormat::Mach3 => Box::new(Mach3Post),
        }
    }
}

/// Get a post-processor by name (CLI backward compatibility).
pub fn get_post_processor(name: &str) -> Option<Box<dyn PostProcessor>> {
    match name.to_lowercase().as_str() {
        "grbl" => Some(PostFormat::Grbl.post_processor()),
        "linuxcnc" => Some(PostFormat::LinuxCnc.post_processor()),
        "mach3" => Some(PostFormat::Mach3.post_processor()),
        _ => None,
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;
    use crate::geo::P3;
    use crate::toolpath::Toolpath;

    #[test]
    fn checked_phased_export_is_byte_identical_to_legacy_emitter() {
        let mut tp1 = Toolpath::new();
        tp1.rapid_to(P3::new(0.0, 0.0, 10.0));
        tp1.feed_to(P3::new(10.0, 0.0, 0.0), 1000.0);

        let mut tp2 = Toolpath::new();
        tp2.rapid_to(P3::new(20.0, 0.0, 10.0));
        tp2.feed_to(P3::new(30.0, 0.0, 0.0), 800.0);

        let phases = vec![
            GcodePhase {
                toolpath: &tp1,
                spindle_rpm: 18_000,
                label: "Op 0 — pocket",
                pre_gcode: Some("M8"),
                post_gcode: Some("M9"),
                tool_number: Some(1),
                coolant: CoolantMode::Mist,
                controller_compensation: None,
            },
            GcodePhase {
                toolpath: &tp2,
                spindle_rpm: 16_000,
                label: "Op 1 — profile",
                pre_gcode: None,
                post_gcode: None,
                tool_number: Some(2),
                coolant: CoolantMode::Off,
                controller_compensation: None,
            },
        ];

        let legacy = emit_gcode_phased(&phases, &GrblPost);
        let checked =
            export_gcode_phases_checked(&phases, &GrblPost, None, ToolLoadExportPolicy::default())
                .expect("checked export should succeed");

        assert_eq!(checked, legacy);
    }

    #[test]
    fn checked_multi_setup_export_is_byte_identical_to_legacy_emitter() {
        let mut tp1 = Toolpath::new();
        tp1.rapid_to(P3::new(0.0, 0.0, 10.0));
        tp1.feed_to(P3::new(10.0, 0.0, 0.0), 1000.0);

        let mut tp2 = Toolpath::new();
        tp2.rapid_to(P3::new(20.0, 0.0, 10.0));
        tp2.feed_to(P3::new(30.0, 0.0, 0.0), 800.0);

        let setups = vec![
            GcodeSetupPhase {
                setup_label: "Top",
                phases: vec![GcodePhase {
                    toolpath: &tp1,
                    spindle_rpm: 18_000,
                    label: "Top pocket",
                    pre_gcode: None,
                    post_gcode: None,
                    tool_number: Some(1),
                    coolant: CoolantMode::Off,
                    controller_compensation: None,
                }],
            },
            GcodeSetupPhase {
                setup_label: "Bottom",
                phases: vec![GcodePhase {
                    toolpath: &tp2,
                    spindle_rpm: 16_000,
                    label: "Bottom profile",
                    pre_gcode: None,
                    post_gcode: None,
                    tool_number: Some(2),
                    coolant: CoolantMode::Flood,
                    controller_compensation: None,
                }],
            },
        ];

        let legacy = emit_gcode_multi_setup(&setups, &GrblPost, 15.0);
        let checked = export_gcode_multi_setup_checked(
            &setups,
            &GrblPost,
            15.0,
            None,
            ToolLoadExportPolicy::default(),
        )
        .expect("checked export should succeed");

        assert_eq!(checked, legacy);
    }

    #[test]
    fn test_grbl_gcode() {
        let mut tp = Toolpath::new();
        tp.rapid_to(P3::new(0.0, 0.0, 10.0));
        tp.feed_to(P3::new(10.0, 0.0, 0.0), 1000.0);
        tp.feed_to(P3::new(20.0, 0.0, 0.0), 1000.0);

        let gcode = emit_gcode(&tp, &GrblPost, 18000);

        assert!(gcode.contains("G17 G21 G90"));
        assert!(gcode.contains("M3 S18000"));
        assert!(gcode.contains("G0 X0.000 Y0.000 Z10.000"));
        assert!(gcode.contains("G1 X10.000 Y0.000 Z0.000 F1000"));
        // Second G1 should omit F (modal)
        assert!(gcode.contains("G1 X20.000 Y0.000 Z0.000\n"));
        assert!(gcode.contains("M5"));
        assert!(gcode.contains("M30"));
    }

    #[test]
    fn test_mach3_gcode() {
        let mut tp = Toolpath::new();
        tp.rapid_to(P3::new(0.0, 0.0, 10.0));
        tp.feed_to(P3::new(10.0, 0.0, 0.0), 1000.0);

        let gcode = emit_gcode(&tp, &Mach3Post, 18000);

        assert!(gcode.contains("G17 G21 G90"));
        assert!(gcode.contains("G4 P2"), "Mach3 should have spindle dwell");
        assert!(gcode.contains("G28 G91 Z0"), "Mach3 should have G28 return");
        assert!(gcode.contains("M30"));
    }

    #[test]
    fn test_grbl_arc_gcode() {
        let mut tp = Toolpath::new();
        tp.rapid_to(P3::new(10.0, 0.0, -3.0));
        tp.arc_cw_to(P3::new(0.0, 10.0, -3.0), -10.0, 0.0, 1000.0);
        tp.arc_ccw_to(P3::new(-10.0, 0.0, -3.0), 0.0, 10.0, 1000.0);

        let gcode = emit_gcode(&tp, &GrblPost, 18000);

        assert!(gcode.contains("G2 X0.000 Y10.000 Z-3.000 I-10.000 J0.000 F1000"));
        assert!(gcode.contains("G3 X-10.000 Y0.000 Z-3.000 I0.000 J10.000 F1000"));
    }

    #[test]
    fn test_get_post_processor() {
        assert!(get_post_processor("grbl").is_some());
        assert!(get_post_processor("linuxcnc").is_some());
        assert!(get_post_processor("mach3").is_some());
        assert!(get_post_processor("unknown").is_none());
    }

    #[test]
    fn test_emit_gcode_phased_same_spindle() {
        let mut tp1 = Toolpath::new();
        tp1.rapid_to(P3::new(0.0, 0.0, 10.0));
        tp1.feed_to(P3::new(10.0, 0.0, 0.0), 1000.0);

        let mut tp2 = Toolpath::new();
        tp2.rapid_to(P3::new(20.0, 0.0, 10.0));
        tp2.feed_to(P3::new(30.0, 0.0, 0.0), 800.0);

        let phases = vec![
            GcodePhase {
                toolpath: &tp1,
                spindle_rpm: 18000,
                label: "Op 0 — pocket",
                pre_gcode: None,
                post_gcode: None,
                tool_number: None,
                coolant: CoolantMode::Off,
                controller_compensation: None,
            },
            GcodePhase {
                toolpath: &tp2,
                spindle_rpm: 18000,
                label: "Op 1 — profile",
                pre_gcode: None,
                post_gcode: None,
                tool_number: None,
                coolant: CoolantMode::Off,
                controller_compensation: None,
            },
        ];
        let gcode = emit_gcode_phased(&phases, &GrblPost);

        // Should have one preamble with M3 S18000
        assert!(gcode.contains("M3 S18000"));
        // Should have both operations' comments
        assert!(gcode.contains("(Op 0"));
        assert!(gcode.contains("(Op 1"));
        // No extra spindle speed change since both are 18000
        let m3_count = gcode.matches("M3 S").count();
        assert_eq!(m3_count, 1, "Same spindle speed should not emit extra M3");
    }

    #[test]
    fn test_emit_gcode_phased_different_spindle() {
        let mut tp1 = Toolpath::new();
        tp1.rapid_to(P3::new(0.0, 0.0, 10.0));
        tp1.feed_to(P3::new(10.0, 0.0, 0.0), 1000.0);

        let mut tp2 = Toolpath::new();
        tp2.rapid_to(P3::new(20.0, 0.0, 10.0));
        tp2.feed_to(P3::new(30.0, 0.0, 0.0), 800.0);

        let phases = vec![
            GcodePhase {
                toolpath: &tp1,
                spindle_rpm: 18000,
                label: "Op 0 — rough",
                pre_gcode: None,
                post_gcode: None,
                tool_number: None,
                coolant: CoolantMode::Off,
                controller_compensation: None,
            },
            GcodePhase {
                toolpath: &tp2,
                spindle_rpm: 24000,
                label: "Op 1 — finish",
                pre_gcode: None,
                post_gcode: None,
                tool_number: None,
                coolant: CoolantMode::Off,
                controller_compensation: None,
            },
        ];
        let gcode = emit_gcode_phased(&phases, &GrblPost);

        // Should have preamble M3 S18000 + later M3 S24000
        assert!(gcode.contains("M3 S18000"));
        assert!(gcode.contains("M3 S24000"));
        let m3_count = gcode.matches("M3 S").count();
        assert_eq!(
            m3_count, 2,
            "Different spindle speeds should emit M3 for each"
        );
    }

    #[test]
    fn per_op_spindle_rpm_drives_phase_emission() {
        // End-to-end: building each `GcodePhase`'s `spindle_rpm` via
        // `effective_spindle_rpm` should emit per-toolpath M3 S<rpm>
        // commands in the resulting G-code. TP0 carries an override of
        // 12000; TP1 falls back to the project default of 18000.
        use crate::compute::catalog::{OperationConfig, effective_spindle_rpm};
        use crate::compute::operation_configs::PocketConfig;

        let mut op_override = OperationConfig::Pocket(PocketConfig::default());
        op_override.set_spindle_rpm(Some(12_000));
        let op_default = OperationConfig::Pocket(PocketConfig::default());
        let project_default_rpm: u32 = 18_000;

        let mut tp1 = Toolpath::new();
        tp1.rapid_to(P3::new(0.0, 0.0, 10.0));
        tp1.feed_to(P3::new(10.0, 0.0, 0.0), 1000.0);

        let mut tp2 = Toolpath::new();
        tp2.rapid_to(P3::new(20.0, 0.0, 10.0));
        tp2.feed_to(P3::new(30.0, 0.0, 0.0), 800.0);

        let phases = vec![
            GcodePhase {
                toolpath: &tp1,
                spindle_rpm: effective_spindle_rpm(&op_override, project_default_rpm),
                label: "TP0 — override",
                pre_gcode: None,
                post_gcode: None,
                tool_number: None,
                coolant: CoolantMode::Off,
                controller_compensation: None,
            },
            GcodePhase {
                toolpath: &tp2,
                spindle_rpm: effective_spindle_rpm(&op_default, project_default_rpm),
                label: "TP1 — default",
                pre_gcode: None,
                post_gcode: None,
                tool_number: None,
                coolant: CoolantMode::Off,
                controller_compensation: None,
            },
        ];
        let gcode = emit_gcode_phased(&phases, &GrblPost);

        assert!(
            gcode.contains("M3 S12000"),
            "TP0's override should produce M3 S12000:\n{gcode}"
        );
        assert!(
            gcode.contains("M3 S18000"),
            "TP1 should fall back to project default 18000:\n{gcode}"
        );
    }

    #[test]
    fn test_program_pause_stops_and_pauses() {
        let pause = GrblPost.program_pause("Rotate stock");
        assert!(pause.contains("M5"));
        assert!(pause.contains("(Rotate stock)"));
        assert!(pause.contains("M0"));
    }

    #[test]
    fn test_emit_gcode_multi_setup_inserts_pause_between_setups() {
        let mut tp1 = Toolpath::new();
        tp1.rapid_to(P3::new(0.0, 0.0, 10.0));
        tp1.feed_to(P3::new(10.0, 0.0, 0.0), 1000.0);

        let mut tp2 = Toolpath::new();
        tp2.rapid_to(P3::new(20.0, 0.0, 10.0));
        tp2.feed_to(P3::new(30.0, 0.0, 0.0), 800.0);

        let setups = vec![
            GcodeSetupPhase {
                setup_label: "Top",
                phases: vec![GcodePhase {
                    toolpath: &tp1,
                    spindle_rpm: 18_000,
                    label: "Pocket",
                    pre_gcode: None,
                    post_gcode: None,
                    tool_number: None,
                    coolant: CoolantMode::Off,
                    controller_compensation: None,
                }],
            },
            GcodeSetupPhase {
                setup_label: "Bottom",
                phases: vec![GcodePhase {
                    toolpath: &tp2,
                    spindle_rpm: 24_000,
                    label: "Profile",
                    pre_gcode: None,
                    post_gcode: None,
                    tool_number: None,
                    coolant: CoolantMode::Off,
                    controller_compensation: None,
                }],
            },
        ];

        let gcode = emit_gcode_multi_setup(&setups, &GrblPost, 15.0);

        assert!(gcode.contains("(=== Top ===)"));
        assert!(gcode.contains("(=== Bottom ===)"));
        assert!(gcode.contains("G0 Z15.000"));
        assert!(gcode.contains("(Setup change: Bottom)"));
        assert!(gcode.contains("M0"));
        assert!(gcode.contains("M3 S18000"));
        assert!(gcode.contains("M3 S24000"));
    }

    #[test]
    fn test_pre_post_gcode_emitted_in_phased() {
        let mut tp = Toolpath::new();
        tp.rapid_to(P3::new(0.0, 0.0, 10.0));
        tp.feed_to(P3::new(10.0, 0.0, 0.0), 1000.0);

        let phases = vec![GcodePhase {
            toolpath: &tp,
            spindle_rpm: 18000,
            label: "Test Op",
            pre_gcode: Some("G55\nG10 L20 P2 X0 Y0 Z0"),
            post_gcode: Some("M9"),
            tool_number: None,
            coolant: CoolantMode::Off,
            controller_compensation: None,
        }];
        let gcode = emit_gcode_phased(&phases, &GrblPost);

        // pre_gcode should appear after the label comment, before moves
        let label_pos = gcode.find("(Test Op)").expect("label comment");
        let pre_pos = gcode.find("G55").expect("pre_gcode G55");
        let move_pos = gcode.find("G0 X0.000").expect("first rapid move");
        let post_pos = gcode.find("M9").expect("post_gcode M9");
        let postamble_pos = gcode.find("M30").expect("postamble");

        assert!(label_pos < pre_pos, "pre_gcode should follow label comment");
        assert!(pre_pos < move_pos, "pre_gcode should precede moves");
        assert!(move_pos < post_pos, "post_gcode should follow moves");
        assert!(
            post_pos < postamble_pos,
            "post_gcode should precede postamble"
        );

        // Verify multi-line pre_gcode is emitted correctly
        assert!(gcode.contains("G10 L20 P2 X0 Y0 Z0"));
    }

    #[test]
    fn test_pre_post_gcode_emitted_in_multi_setup() {
        let mut tp = Toolpath::new();
        tp.rapid_to(P3::new(0.0, 0.0, 10.0));
        tp.feed_to(P3::new(10.0, 0.0, 0.0), 1000.0);

        let setups = vec![GcodeSetupPhase {
            setup_label: "Top",
            phases: vec![GcodePhase {
                toolpath: &tp,
                spindle_rpm: 18_000,
                label: "Pocket",
                pre_gcode: Some("G55"),
                post_gcode: Some("M9"),
                tool_number: None,
                coolant: CoolantMode::Off,
                controller_compensation: None,
            }],
        }];

        let gcode = emit_gcode_multi_setup(&setups, &GrblPost, 15.0);

        let label_pos = gcode.find("(Pocket)").expect("label comment");
        let pre_pos = gcode.find("G55").expect("pre_gcode G55");
        let move_pos = gcode.find("G0 X0.000").expect("first rapid move");
        let post_pos = gcode.find("M9").expect("post_gcode M9");

        assert!(label_pos < pre_pos);
        assert!(pre_pos < move_pos);
        assert!(move_pos < post_pos);
    }

    #[test]
    fn test_empty_pre_post_gcode_omitted() {
        let mut tp = Toolpath::new();
        tp.rapid_to(P3::new(0.0, 0.0, 10.0));

        let phases = vec![GcodePhase {
            toolpath: &tp,
            spindle_rpm: 18000,
            label: "Empty",
            pre_gcode: Some(""),
            post_gcode: None,
            tool_number: None,
            coolant: CoolantMode::Off,
            controller_compensation: None,
        }];
        let gcode = emit_gcode_phased(&phases, &GrblPost);

        // Should not have extra blank lines from empty pre/post
        let lines: Vec<&str> = gcode.lines().collect();
        assert!(
            !lines.iter().any(|l| l.is_empty()),
            "No blank lines from empty pre/post gcode"
        );
    }

    #[test]
    fn test_m6_tool_change_between_phases() {
        let mut tp1 = Toolpath::new();
        tp1.rapid_to(P3::new(0.0, 0.0, 10.0));
        tp1.feed_to(P3::new(10.0, 0.0, 0.0), 1000.0);

        let mut tp2 = Toolpath::new();
        tp2.rapid_to(P3::new(20.0, 0.0, 10.0));
        tp2.feed_to(P3::new(30.0, 0.0, 0.0), 800.0);

        let phases = vec![
            GcodePhase {
                toolpath: &tp1,
                spindle_rpm: 18000,
                label: "Op 0 — 6mm endmill",
                pre_gcode: None,
                post_gcode: None,
                tool_number: Some(1),
                coolant: CoolantMode::Off,
                controller_compensation: None,
            },
            GcodePhase {
                toolpath: &tp2,
                spindle_rpm: 24000,
                label: "Op 1 — 3mm ballnose",
                pre_gcode: None,
                post_gcode: None,
                tool_number: Some(2),
                coolant: CoolantMode::Off,
                controller_compensation: None,
            },
        ];
        let gcode = emit_gcode_phased(&phases, &GrblPost);

        // M6 T2 should appear between the two phases
        assert!(
            gcode.contains("M6 T2"),
            "Should emit M6 T2 for tool change to tool 2"
        );
        // M5 should appear before the tool change (spindle stop)
        let m5_pos = gcode.find("M5\nM6").expect("M5 before M6");
        let m6_pos = gcode.find("M6 T2").expect("M6 T2");
        assert!(m5_pos < m6_pos, "M5 should precede M6");

        // M3 S24000 should appear after the tool change (spindle restart)
        let m3_pos = gcode[m6_pos..].find("M3 S24000").expect("M3 after M6");
        assert!(m3_pos > 0, "M3 should follow M6");

        // No M6 T1 — first tool is assumed already loaded
        assert!(
            !gcode.contains("M6 T1"),
            "First tool should not emit M6 (already loaded)"
        );
    }

    #[test]
    fn test_no_m6_when_same_tool() {
        let mut tp1 = Toolpath::new();
        tp1.rapid_to(P3::new(0.0, 0.0, 10.0));

        let mut tp2 = Toolpath::new();
        tp2.rapid_to(P3::new(20.0, 0.0, 10.0));

        let phases = vec![
            GcodePhase {
                toolpath: &tp1,
                spindle_rpm: 18000,
                label: "Op 0",
                pre_gcode: None,
                post_gcode: None,
                tool_number: Some(1),
                coolant: CoolantMode::Off,
                controller_compensation: None,
            },
            GcodePhase {
                toolpath: &tp2,
                spindle_rpm: 18000,
                label: "Op 1",
                pre_gcode: None,
                post_gcode: None,
                tool_number: Some(1),
                coolant: CoolantMode::Off,
                controller_compensation: None,
            },
        ];
        let gcode = emit_gcode_phased(&phases, &GrblPost);

        assert!(!gcode.contains("M6"), "Same tool number should not emit M6");
    }

    #[test]
    fn test_coolant_mist_m7() {
        let mut tp = Toolpath::new();
        tp.rapid_to(P3::new(0.0, 0.0, 10.0));
        tp.feed_to(P3::new(10.0, 0.0, 0.0), 1000.0);

        let phases = vec![GcodePhase {
            toolpath: &tp,
            spindle_rpm: 18000,
            label: "Mist coolant op",
            pre_gcode: None,
            post_gcode: None,
            tool_number: None,
            coolant: CoolantMode::Mist,
            controller_compensation: None,
        }];
        let gcode = emit_gcode_phased(&phases, &GrblPost);

        assert!(gcode.contains("M7"), "Mist coolant should emit M7");
        assert!(gcode.contains("M9"), "Should emit M9 before postamble");

        // M7 should appear before moves, M9 before postamble
        let m7_pos = gcode.find("M7").expect("M7");
        let move_pos = gcode.find("G0 X0.000").expect("move");
        let m9_pos = gcode.find("M9").expect("M9");
        let m5_pos = gcode.rfind("M5").expect("M5 in postamble");
        assert!(m7_pos < move_pos, "M7 should precede moves");
        assert!(m9_pos < m5_pos, "M9 should precede postamble M5");
    }

    #[test]
    fn test_coolant_flood_m8() {
        let mut tp = Toolpath::new();
        tp.rapid_to(P3::new(0.0, 0.0, 10.0));

        let phases = vec![GcodePhase {
            toolpath: &tp,
            spindle_rpm: 18000,
            label: "Flood coolant op",
            pre_gcode: None,
            post_gcode: None,
            tool_number: None,
            coolant: CoolantMode::Flood,
            controller_compensation: None,
        }];
        let gcode = emit_gcode_phased(&phases, &GrblPost);

        assert!(gcode.contains("M8"), "Flood coolant should emit M8");
        assert!(gcode.contains("M9"), "Should emit M9 before postamble");
    }

    #[test]
    fn test_coolant_both_m7_m8() {
        let mut tp = Toolpath::new();
        tp.rapid_to(P3::new(0.0, 0.0, 10.0));

        let phases = vec![GcodePhase {
            toolpath: &tp,
            spindle_rpm: 18000,
            label: "Both coolant op",
            pre_gcode: None,
            post_gcode: None,
            tool_number: None,
            coolant: CoolantMode::Both,
            controller_compensation: None,
        }];
        let gcode = emit_gcode_phased(&phases, &GrblPost);

        assert!(gcode.contains("M7"), "Both mode should emit M7");
        assert!(gcode.contains("M8"), "Both mode should emit M8");
        assert!(gcode.contains("M9"), "Should emit M9 before postamble");
    }

    #[test]
    fn test_coolant_off_no_commands() {
        let mut tp = Toolpath::new();
        tp.rapid_to(P3::new(0.0, 0.0, 10.0));

        let phases = vec![GcodePhase {
            toolpath: &tp,
            spindle_rpm: 18000,
            label: "No coolant",
            pre_gcode: None,
            post_gcode: None,
            tool_number: None,
            coolant: CoolantMode::Off,
            controller_compensation: None,
        }];
        let gcode = emit_gcode_phased(&phases, &GrblPost);

        assert!(!gcode.contains("M7"), "Off should not emit M7");
        assert!(!gcode.contains("M8"), "Off should not emit M8");
        assert!(!gcode.contains("M9"), "Off should not emit M9");
    }

    #[test]
    fn test_tool_change_with_coolant() {
        let mut tp1 = Toolpath::new();
        tp1.rapid_to(P3::new(0.0, 0.0, 10.0));

        let mut tp2 = Toolpath::new();
        tp2.rapid_to(P3::new(20.0, 0.0, 10.0));

        let phases = vec![
            GcodePhase {
                toolpath: &tp1,
                spindle_rpm: 18000,
                label: "Op 0",
                pre_gcode: None,
                post_gcode: None,
                tool_number: Some(1),
                coolant: CoolantMode::Flood,
                controller_compensation: None,
            },
            GcodePhase {
                toolpath: &tp2,
                spindle_rpm: 24000,
                label: "Op 1",
                pre_gcode: None,
                post_gcode: None,
                tool_number: Some(2),
                coolant: CoolantMode::Mist,
                controller_compensation: None,
            },
        ];
        let gcode = emit_gcode_phased(&phases, &GrblPost);

        // Should have M8 for first phase, M9 before tool change, M6 T2, M3, M7 for second
        assert!(gcode.contains("M8"), "First phase should have M8 flood");
        assert!(gcode.contains("M6 T2"), "Should have tool change");
        assert!(gcode.contains("M7"), "Second phase should have M7 mist");
        // M9 should appear before M6 (coolant off before tool change)
        let m9_pos = gcode.find("M9").expect("M9");
        let m6_pos = gcode.find("M6 T2").expect("M6 T2");
        assert!(
            m9_pos < m6_pos,
            "M9 should precede M6 (coolant off before tool change)"
        );
    }

    // ----- enforce_load_policy negative tests -----

    use crate::tool_load::verdict::{
        ChipBounds, ChipBoundsSource, ChiploadMetric, ChiploadStatistic, DeflectionBounds,
        SampleEvidence,
    };
    use crate::tool_load::{
        ChiploadVerdict, Confidence, DeflectionVerdict, PowerVerdict, ToolLoadReport,
        ToolpathLoadVerdict, UnmodeledReason,
    };

    fn report_with(
        chipload: ChiploadVerdict,
        power: PowerVerdict,
        deflection: DeflectionVerdict,
    ) -> ToolLoadReport {
        ToolLoadReport {
            per_toolpath: vec![ToolpathLoadVerdict {
                toolpath_id: 4,
                chipload,
                power,
                deflection,
            }],
        }
    }

    fn chip_bounds() -> ChipBounds {
        ChipBounds {
            min_mm_per_tooth: Some(0.038),
            max_mm_per_tooth: 0.07,
            source: ChipBoundsSource::VendorLut,
        }
    }

    fn chipload_within(peak: f64) -> ChiploadVerdict {
        ChiploadVerdict::Within {
            approach_to_min: None,
            approach_to_max: ChiploadMetric {
                observed_mm_per_tooth: peak,
                statistic: ChiploadStatistic::PeakInRange,
                evidence: SampleEvidence::empty(),
                bounds: chip_bounds(),
            },
            confidence: Confidence::Validated,
        }
    }

    fn chipload_unmodeled(reason: UnmodeledReason) -> ChiploadVerdict {
        ChiploadVerdict::Unmodeled { reason }
    }

    fn power_not_implemented() -> PowerVerdict {
        PowerVerdict::Unmodeled {
            reason: UnmodeledReason::NotImplemented("phase 1b".to_owned()),
        }
    }

    fn deflection_bounds_default() -> DeflectionBounds {
        DeflectionBounds {
            validated_within_mm: 0.050,
            exceeds_mm: 0.200,
        }
    }

    fn deflection_within(peak_mm: f64) -> DeflectionVerdict {
        DeflectionVerdict::Within {
            peak_mm,
            bounds: deflection_bounds_default(),
            evidence: SampleEvidence::empty(),
            confidence: Confidence::Validated,
        }
    }

    fn deflection_exceeds(peak_mm: f64) -> DeflectionVerdict {
        DeflectionVerdict::Exceeds {
            peak_mm,
            bounds: deflection_bounds_default(),
            evidence: SampleEvidence::at(0),
            confidence: Confidence::Validated,
        }
    }

    #[test]
    fn enforce_blocks_exceeded_by_default() {
        let report = report_with(
            chipload_within(0.05),
            power_not_implemented(),
            deflection_exceeds(10.0),
        );
        let policy = ToolLoadExportPolicy::default();
        let err =
            enforce_load_policy(&report, &policy).expect_err("default policy must block Exceeds");
        let msg = err.to_string();
        assert!(
            msg.contains("toolpath 4"),
            "error names the toolpath: {msg}"
        );
        assert!(
            msg.contains("deflection"),
            "error names the criterion: {msg}"
        );
        assert!(msg.contains("stiffness"), "error names the reason: {msg}");
    }

    #[test]
    fn enforce_lets_exceeded_through_only_with_explicit_flag() {
        // Same scenario, but with accept_exceeded=true. Note unmodeled is
        // also true — if it weren't, the report's unmodeled chipload/power
        // criteria would still block. Verify the two flags are distinct.
        let report = report_with(
            chipload_within(0.05),
            power_not_implemented(),
            deflection_exceeds(10.0),
        );

        // accept_unmodeled alone is NOT enough — Exceeds still blocks.
        let policy_u = ToolLoadExportPolicy {
            accept_unmodeled: true,
            accept_exceeded: false,
        };
        assert!(
            enforce_load_policy(&report, &policy_u).is_err(),
            "accept_unmodeled alone must not bypass Exceeds"
        );

        // accept_exceeded alone bypasses Exceeds, but unmodeled still blocks
        // (chipload+power are NotImplemented).
        let policy_e = ToolLoadExportPolicy {
            accept_unmodeled: false,
            accept_exceeded: true,
        };
        assert!(
            enforce_load_policy(&report, &policy_e).is_err(),
            "Exceeds bypassed but Unmodeled still blocks"
        );

        // Both flags accept everything.
        let policy_both = ToolLoadExportPolicy {
            accept_unmodeled: true,
            accept_exceeded: true,
        };
        assert!(enforce_load_policy(&report, &policy_both).is_ok());
    }

    #[test]
    fn enforce_blocks_unmodeled_by_default() {
        let report = report_with(
            chipload_unmodeled(UnmodeledReason::NotImplemented("phase 5".to_owned())),
            power_not_implemented(),
            deflection_within(3.0),
        );
        let err = enforce_load_policy(&report, &ToolLoadExportPolicy::default())
            .expect_err("Unmodeled must block by default");
        let msg = err.to_string();
        assert!(msg.contains("toolpath 4"), "names toolpath: {msg}");
        assert!(msg.contains("chipload"), "names unmodeled criterion: {msg}");
    }

    #[test]
    fn enforce_passes_when_all_within() {
        let report = report_with(
            chipload_within(0.05),
            PowerVerdict::Within {
                peak_kw: 0.5,
                available_kw: 0.71,
                evidence: SampleEvidence::empty(),
                confidence: Confidence::Approximate("isotropic Kc only".into()),
            },
            deflection_within(3.5),
        );
        assert!(
            enforce_load_policy(&report, &ToolLoadExportPolicy::default()).is_ok(),
            "all-Within report must pass"
        );
    }

    #[test]
    fn enforce_distinguishes_unmodeled_reasons() {
        // Different `Unmodeled` reasons produce different error messages so
        // the user knows whether to "run sim" vs "this material has no LUT".
        let r1 = report_with(
            chipload_unmodeled(UnmodeledReason::SimulationRequired),
            power_not_implemented(),
            deflection_within(3.0),
        );
        let r2 = report_with(
            chipload_unmodeled(UnmodeledReason::NoVendorData),
            power_not_implemented(),
            deflection_within(3.0),
        );
        let m1 = enforce_load_policy(&r1, &ToolLoadExportPolicy::default())
            .expect_err("blocks")
            .to_string();
        let m2 = enforce_load_policy(&r2, &ToolLoadExportPolicy::default())
            .expect_err("blocks")
            .to_string();
        assert!(m1.contains("SimulationRequired"));
        assert!(m2.contains("NoVendorData"));
    }
}
