//! The By Area regions overlay (operator, 2026-09-24: "Is there a way we
//! can add an overlay to identify the detected areas?").
//!
//! - the registry row `area_regions` is off by default, and it draws only
//!   for the SELECTED toolpath (WP27) when that toolpath carries a region
//!   map;
//! - a Global 3D Rough, an ungenerated By Area 3D Rough and another
//!   operation each get their own disabled reason;
//! - the legend rail shows one entry per region, in the region colour that
//!   the mesh draws;
//! - the viewport callback reads the same gate.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing
)]

use std::path::{Path, PathBuf};
use std::sync::Arc;

use rs_cam_core::ToolpathId;
use rs_cam_core::adaptive3d::{AreaRegion, AreaRegionMap};
use rs_cam_core::compute::catalog::OperationConfig;
use rs_cam_core::compute::operation_configs::{Adaptive3dConfig, RegionOrdering};
use rs_cam_core::compute::tool_config::{ToolConfig, ToolId, ToolType};
use rs_cam_core::geo::P3;
use rs_cam_core::maps::rest_heatmap_mesh::{area_region_color, area_regions_to_mesh};
use rs_cam_core::session::{
    AddToolpathArgs, Command, LoadedModel, ProjectSessionBuilder, ToolpathConfig,
};
use rs_cam_core::toolpath::Toolpath;
use rs_cam_core::trace::toolpath_spans::AnnotatedToolpath;
use rs_cam_viz::state::runtime::{ComputeStatus, ToolpathRuntime};
use rs_cam_viz::state::selection::Selection;
use rs_cam_viz::state::toolpath::ToolpathResult;
use rs_cam_viz::state::{AppState, Workspace};
use rs_cam_viz::ui::overlays::legend_rail::{self, Categories, RailLine};
use rs_cam_viz::ui::overlays::registry;

const TOOL: usize = 1;
const MODEL: usize = 4;

fn fresh_state() -> AppState {
    let mut state = AppState::new();
    let mut tool = ToolConfig::new_default(ToolId(TOOL), ToolType::EndMill);
    tool.diameter = 6.0;
    state.session = ProjectSessionBuilder::new()
        .tool(tool)
        .model(LoadedModel {
            id: MODEL,
            path: PathBuf::from("model.stl"),
            name: "3D".to_owned(),
            kind: None,
            mesh: None,
            polygons: None,
            drill_targets: Arc::new(Vec::new()),
            layers: Arc::new(Vec::new()),
            enriched_mesh: None,
            units: None,
            winding_report: None,
            load_error: None,
        })
        .build();
    state.workspace = Workspace::Toolpaths;
    state
}

fn config(operation: OperationConfig) -> ToolpathConfig {
    ToolpathConfig {
        id: ToolpathId(0),
        name: "Rough".to_owned(),
        enabled: true,
        operation,
        dressups: Default::default(),
        heights: Default::default(),
        tool_id: TOOL,
        model_id: MODEL,
        pre_gcode: None,
        post_gcode: None,
        boundary: Default::default(),
        boundary_inherit: true,
        stock_source: Default::default(),
        coolant: Default::default(),
        face_selection: None,
        debug_options: Default::default(),
        feeds_provenance: Default::default(),
        rest_analysis: Default::default(),
        planner_origin: None,
    }
}

fn rough(ordering: RegionOrdering) -> OperationConfig {
    let cfg = Adaptive3dConfig {
        region_ordering: ordering,
        ..Adaptive3dConfig::default()
    };
    OperationConfig::Adaptive3d(cfg)
}

fn region(order: u16, cell_count: usize, bbox_xy: [f64; 4]) -> AreaRegion {
    AreaRegion {
        order,
        cell_count,
        bbox_xy,
        surface_z_range: [0.0, 1.0],
        level_z_range: Some([8.0, 2.0]),
        level_count: 4,
        anchor_xy: [
            (bbox_xy[0] + bbox_xy[2]) * 0.5,
            (bbox_xy[1] + bbox_xy[3]) * 0.5,
        ],
    }
}

/// Two regions on a 4 x 6 grid of 1 mm cells: region 1 is columns 0..3 of
/// every row (12 cells), region 2 is columns 4..6 of rows 1..3 (4 cells).
fn two_region_map() -> AreaRegionMap {
    let (rows, cols) = (4, 6);
    let mut labels = vec![0u16; rows * cols];
    for row in 0..rows {
        for col in 0..cols {
            labels[row * cols + col] = if col < 3 {
                1
            } else if col >= 4 && (1..3).contains(&row) {
                2
            } else {
                0
            };
        }
    }
    AreaRegionMap {
        origin_x: 0.0,
        origin_y: 0.0,
        cell_mm: 1.0,
        rows,
        cols,
        labels,
        top_z: 10.0,
        regions: vec![
            region(1, 12, [-0.5, -0.5, 2.5, 3.5]),
            region(2, 4, [3.5, 0.5, 5.5, 2.5]),
        ],
    }
}

fn sample_path() -> Toolpath {
    let mut path = Toolpath::new();
    path.rapid_to(P3::new(0.0, 0.0, 12.0));
    path.feed_to(P3::new(2.0, 0.0, 8.0), 600.0);
    path.rapid_to(P3::new(2.0, 0.0, 12.0));
    path
}

/// Add a toolpath with `operation`, give it a result (with `map`, if any),
/// and return its id. `generated = false` leaves it without a result.
fn add(
    state: &mut AppState,
    operation: OperationConfig,
    map: Option<AreaRegionMap>,
    generated: bool,
) -> ToolpathId {
    let index = state
        .session
        .apply(Command::AddToolpath(AddToolpathArgs {
            setup_index: 0,
            config: Box::new(config(operation)),
        }))
        .unwrap()
        .created
        .expect("the AddToolpath row reports the new index");
    let id = state.session.toolpath_configs()[index].id;
    let mut rt = ToolpathRuntime::new(true);
    if generated {
        rt.status = ComputeStatus::Done;
        let mut annotated = AnnotatedToolpath::new(sample_path());
        annotated.area_regions = map.map(Arc::new);
        rt.result = Some(ToolpathResult {
            annotated: Arc::new(annotated),
            stats: Default::default(),
            debug_trace: None,
            semantic_trace: None,
            debug_trace_path: None,
            drill_op: None,
        });
    }
    state.gui.toolpath_rt.insert(id, rt);
    id
}

fn row() -> &'static registry::OverlayRow {
    registry::row("area_regions").expect("the By Area regions row is registered")
}

fn reason(state: &AppState) -> String {
    (row().precondition)(state)
        .reason()
        .unwrap_or_default()
        .to_owned()
}

#[test]
fn the_row_toggles_and_draws_for_the_selected_toolpath_only() {
    let mut state = fresh_state();
    let by_area = add(
        &mut state,
        rough(RegionOrdering::ByArea),
        Some(two_region_map()),
        true,
    );
    let other = add(&mut state, rough(RegionOrdering::ByArea), None, false);

    // Off by default, in every workspace.
    assert!(!state.viewport.show_area_regions);
    assert_eq!((row().default_for)(Workspace::Toolpaths), None);
    assert_eq!(row().label, "By Area regions");

    // Nothing selected: the row cannot draw.
    state.selection = Selection::None;
    assert!(!(row().precondition)(&state).is_ready());
    assert!(
        reason(&state).contains("select a 3D Rough"),
        "{}",
        reason(&state)
    );

    // The By Area toolpath is selected: the row switches on and draws.
    state.selection = Selection::Toolpath(by_area);
    assert!((row().precondition)(&state).is_ready());
    registry::set_overlay(&mut state, row(), true);
    assert!(state.viewport.show_area_regions);
    assert!(registry::area_regions_drawn(&state));
    let map = registry::selected_area_regions(&state).expect("the selected map");
    assert_eq!(map.regions.len(), 2);

    // Another toolpath is selected: the first map does not draw (WP27).
    state.selection = Selection::Toolpath(other);
    assert!(!registry::area_regions_drawn(&state));
    assert!(registry::selected_area_regions(&state).is_none());
    assert!(reason(&state).contains("generate"), "{}", reason(&state));

    // Back on the By Area toolpath, the Simulation workspace refuses it.
    state.selection = Selection::Toolpath(by_area);
    state.workspace = Workspace::Simulation;
    assert!(!registry::area_regions_drawn(&state));
    assert!(reason(&state).contains("Toolpaths workspace"));
    state.workspace = Workspace::Toolpaths;

    // The row switches off again.
    registry::set_overlay(&mut state, row(), false);
    assert!(!state.viewport.show_area_regions);
    assert!(!registry::area_regions_drawn(&state));
}

#[test]
fn global_ordering_and_other_operations_say_why_nothing_draws() {
    let mut state = fresh_state();
    let global = add(&mut state, rough(RegionOrdering::Global), None, true);
    state.selection = Selection::Toolpath(global);
    registry::set_overlay(&mut state, row(), true);
    assert!(!registry::area_regions_drawn(&state));
    assert!(reason(&state).contains("Global"), "{}", reason(&state));

    let pocket = add(
        &mut state,
        OperationConfig::Pocket(Default::default()),
        None,
        true,
    );
    state.selection = Selection::Toolpath(pocket);
    assert!(
        reason(&state).contains("not a 3D Rough"),
        "{}",
        reason(&state)
    );
}

#[test]
fn the_legend_names_each_region_in_its_mesh_colour() {
    let mut state = fresh_state();
    let id = add(
        &mut state,
        rough(RegionOrdering::ByArea),
        Some(two_region_map()),
        true,
    );
    state.selection = Selection::Toolpath(id);
    let lines = legend_rail::active_lines(&state);
    assert!(
        !lines.contains(&RailLine::Categories(Categories::AreaRegions)),
        "no legend while the row is off"
    );

    registry::set_overlay(&mut state, row(), true);
    let lines = legend_rail::active_lines(&state);
    assert!(lines.contains(&RailLine::Categories(Categories::AreaRegions)));
    let entries = legend_rail::category_entries(&state, Categories::AreaRegions);
    assert_eq!(entries.len(), 2);
    assert!(
        entries[0].0.starts_with("1 \u{00B7} 12 cells"),
        "{entries:?}"
    );
    assert_eq!(entries[0].1, area_region_color(1));
    assert_eq!(entries[1].1, area_region_color(2));
    assert_ne!(area_region_color(1), area_region_color(2));

    // A By Area run that found no region names that on the rail.
    let empty = add(
        &mut state,
        rough(RegionOrdering::ByArea),
        Some(AreaRegionMap {
            regions: Vec::new(),
            labels: vec![0; 24],
            ..two_region_map()
        }),
        true,
    );
    state.selection = Selection::Toolpath(empty);
    let entries = legend_rail::category_entries(&state, Categories::AreaRegions);
    assert_eq!(
        entries,
        vec![("no region detected".to_owned(), None)],
        "the empty legend says so"
    );

    // The mesh paints the same colours: one quad per row run.
    let map = two_region_map();
    let mesh = area_regions_to_mesh(&map).expect("two regions make a mesh");
    let runs = map.row_runs();
    assert_eq!(
        runs.len(),
        4 + 2,
        "region 1: one run per row; region 2: two"
    );
    assert_eq!(mesh.indices.len(), runs.len() * 6);
    let first = area_region_color(runs[0].order).unwrap();
    assert_eq!(&mesh.colors[0..3], &first);
}

#[test]
fn the_viewport_callback_reads_the_one_gate() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("src/app/viewport.rs");
    let text = std::fs::read_to_string(&path).unwrap();
    assert!(text.len() > 500, "non-vacuity: viewport.rs was read");
    assert!(text.contains("registry::area_regions_drawn(state)"));
    assert!(text.contains("show_area_regions: area_regions_drawn,"));
}
